CREATE TABLE `service_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `public_reference` varchar(24) NOT NULL,
  `requester_user_id` int,
  `requester_contact_snapshot` json,
  `taxonomy_node_id` int NOT NULL,
  `title` varchar(200),
  `description` text,
  `timeline_band` enum('asap','within_weeks','within_month','this_quarter','flexible'),
  `budget_band` enum('under_5k','band_5k_15k','band_15k_50k','band_50k_plus','not_sure'),
  `province_id` int,
  `city_id` int,
  `suburb_id` int,
  `location_text` varchar(320),
  `property_id` int,
  `listing_id` int,
  `development_id` int,
  `journey_stage` enum('browsing','buying','selling_prep','selling_active','owning','renting','renting_out','developing','managing_property','improving'),
  `source_surface` enum('services_direct','listing','property','development','location_page','explore','agent_workspace','developer_workspace','property_management') NOT NULL DEFAULT 'services_direct',
  `origin_type` varchar(60),
  `origin_id` int,
  `reason_code` varchar(80),
  `status` enum('open','routing','introduced','connected','closed_matched','closed_no_match','cancelled') NOT NULL DEFAULT 'open',
  `context_json` json,
  `closed_at` timestamp,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_service_requests_public_reference` UNIQUE (`public_reference`),
  KEY `idx_service_requests_requester` (`requester_user_id`),
  KEY `idx_service_requests_status` (`status`),
  KEY `idx_service_requests_node` (`taxonomy_node_id`),
  KEY `idx_service_requests_geo` (`province_id`,`city_id`,`suburb_id`),
  KEY `idx_service_requests_created` (`created_at`),
  CONSTRAINT `fk_service_requests_requester` FOREIGN KEY (`requester_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_node` FOREIGN KEY (`taxonomy_node_id`) REFERENCES `service_taxonomy_nodes` (`id`),
  CONSTRAINT `fk_service_requests_province` FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_suburb` FOREIGN KEY (`suburb_id`) REFERENCES `suburbs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_property` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_listing` FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_service_requests_development` FOREIGN KEY (`development_id`) REFERENCES `developments` (`id`) ON DELETE SET NULL
);
