INSERT INTO `service_taxonomy_nodes` (`id`, `parent_id`, `slug`, `level`, `name`, `description`, `icon_key`, `is_active`, `sort_order`) VALUES
(1, NULL, 'home-improvement', 'family', 'Home Improvement', NULL, 'Hammer', 1, 1),
(2, NULL, 'finance-legal', 'family', 'Finance & Legal', NULL, 'Scale', 1, 2),
(3, NULL, 'moving-relocation', 'family', 'Moving & Relocation', NULL, 'Truck', 1, 3),
(4, NULL, 'inspection-compliance', 'family', 'Inspection & Compliance', NULL, 'ClipboardCheck', 1, 4),
(5, NULL, 'insurance-protection', 'family', 'Insurance & Cover', NULL, 'ShieldCheck', 1, 5),
(6, NULL, 'media-marketing', 'family', 'Media & Marketing', NULL, 'Camera', 1, 6),
(7, NULL, 'professional-services', 'family', 'Professional Services', NULL, 'DraftingCompass', 1, 7),
(10, 1, 'electrical', 'category', 'Electrical', NULL, NULL, 1, 1),
(11, 1, 'plumbing', 'category', 'Plumbing', NULL, NULL, 1, 2),
(12, 1, 'painting-decorating', 'category', 'Painting & Decorating', NULL, NULL, 1, 3),
(13, 1, 'renovations-alterations', 'category', 'Renovations & Alterations', NULL, NULL, 1, 4),
(14, 1, 'solar-backup-power', 'category', 'Solar & Backup Power', NULL, NULL, 1, 5),
(15, 1, 'building-contracting', 'category', 'Building & Contracting', NULL, NULL, 1, 6),
(20, 2, 'home-finance', 'category', 'Home Finance', NULL, NULL, 1, 1),
(21, 2, 'conveyancing-transfer', 'category', 'Conveyancing & Transfer', NULL, NULL, 1, 2),
(22, 2, 'property-legal-advice', 'category', 'Property Legal Advice', NULL, NULL, 1, 3),
(30, 3, 'household-moves', 'category', 'Household Moves', NULL, NULL, 1, 1),
(31, 3, 'specialist-moves', 'category', 'Specialist Moves', NULL, NULL, 1, 2),
(32, 3, 'storage-logistics', 'category', 'Storage & Logistics', NULL, NULL, 1, 3),
(40, 4, 'property-inspections', 'category', 'Property Inspections', NULL, NULL, 1, 1),
(41, 4, 'compliance-certificates', 'category', 'Compliance Certificates', NULL, NULL, 1, 2),
(42, 4, 'energy-efficiency', 'category', 'Energy Efficiency', NULL, NULL, 1, 3),
(50, 5, 'buildings-cover', 'category', 'Buildings Cover', NULL, NULL, 1, 1),
(51, 5, 'contents-cover', 'category', 'Contents Cover', NULL, NULL, 1, 2),
(52, 5, 'landlord-cover', 'category', 'Landlord Cover', NULL, NULL, 1, 3),
(60, 6, 'listing-photography', 'category', 'Listing Photography', NULL, NULL, 1, 1),
(61, 6, 'video-tours', 'category', 'Video Tours', NULL, NULL, 1, 2),
(62, 6, 'home-staging', 'category', 'Home Staging', NULL, NULL, 1, 3),
(63, 6, 'aerial-drone-media', 'category', 'Aerial & Drone Media', NULL, NULL, 1, 4),
(70, 7, 'architecture', 'category', 'Architecture', NULL, NULL, 1, 1),
(71, 7, 'structural-engineering', 'category', 'Structural Engineering', NULL, NULL, 1, 2),
(72, 7, 'project-management', 'category', 'Project Management', NULL, NULL, 1, 3),
(73, 7, 'land-surveying', 'category', 'Land Surveying', NULL, NULL, 1, 4),
(100, 10, 'electrical-installations', 'service', 'Electrical Installations', NULL, NULL, 1, 1),
(101, 10, 'electrical-fault-repairs', 'service', 'Electrical Fault Repairs', NULL, NULL, 1, 2),
(102, 10, 'lighting-installations', 'service', 'Lighting Installations', NULL, NULL, 1, 3),
(110, 11, 'plumbing-repairs', 'service', 'Plumbing Repairs', NULL, NULL, 1, 1),
(111, 11, 'bathroom-kitchen-plumbing', 'service', 'Bathroom & Kitchen Plumbing', NULL, NULL, 1, 2),
(112, 11, 'geyser-installation-repair', 'service', 'Geyser Installation & Repair', NULL, NULL, 1, 3),
(120, 12, 'interior-painting', 'service', 'Interior Painting', NULL, NULL, 1, 1),
(121, 12, 'exterior-painting', 'service', 'Exterior Painting', NULL, NULL, 1, 2),
(130, 13, 'kitchen-renovations', 'service', 'Kitchen Renovations', NULL, NULL, 1, 1),
(131, 13, 'bathroom-renovations', 'service', 'Bathroom Renovations', NULL, NULL, 1, 2),
(132, 13, 'home-additions', 'service', 'Home Additions', NULL, NULL, 1, 3),
(140, 14, 'solar-panel-installation', 'service', 'Solar Panel Installation', NULL, NULL, 1, 1),
(141, 14, 'inverter-battery-backup', 'service', 'Inverter & Battery Backup', NULL, NULL, 1, 2),
(150, 15, 'alterations-outbuildings', 'service', 'Alterations & Outbuildings', NULL, NULL, 1, 1),
(151, 15, 'waterproofing', 'service', 'Waterproofing', NULL, NULL, 1, 2),
(200, 20, 'bond-origination', 'service', 'Bond Origination', NULL, NULL, 1, 1),
(201, 20, 'bond-prequalification', 'service', 'Bond Prequalification', NULL, NULL, 1, 2),
(210, 21, 'property-transfers', 'service', 'Property Transfers', NULL, NULL, 1, 1),
(220, 22, 'lease-agreements', 'service', 'Lease Agreements', NULL, NULL, 1, 1),
(221, 22, 'purchase-contract-review', 'service', 'Purchase Contract Review', NULL, NULL, 1, 2),
(300, 30, 'local-household-moves', 'service', 'Local Household Moves', NULL, NULL, 1, 1),
(301, 30, 'long-distance-moves', 'service', 'Long-Distance Moves', NULL, NULL, 1, 2),
(302, 30, 'packing-services', 'service', 'Packing Services', NULL, NULL, 1, 3),
(310, 31, 'fragile-speciality-moves', 'service', 'Fragile & Speciality Moves', NULL, NULL, 1, 1),
(320, 32, 'short-term-storage', 'service', 'Short-Term Storage', NULL, NULL, 1, 1),
(400, 40, 'pre-purchase-inspections', 'service', 'Pre-Purchase Inspections', NULL, NULL, 1, 1),
(401, 40, 'snag-inspections', 'service', 'Snag Inspections', NULL, NULL, 1, 2),
(402, 40, 'rental-inspections', 'service', 'Rental Inspections', NULL, NULL, 1, 3),
(410, 41, 'electrical-coc', 'service', 'Electrical COC', NULL, NULL, 1, 1),
(411, 41, 'gas-compliance-certificate', 'service', 'Gas Compliance Certificate', NULL, NULL, 1, 2),
(412, 41, 'electric-fence-certificate', 'service', 'Electric Fence Certificate', NULL, NULL, 1, 3),
(420, 42, 'energy-audits', 'service', 'Energy Audits', NULL, NULL, 1, 1),
(500, 50, 'homeowners-buildings-cover', 'service', 'Homeowners Buildings Cover', NULL, NULL, 1, 1),
(510, 51, 'household-contents-cover', 'service', 'Household Contents Cover', NULL, NULL, 1, 1),
(520, 52, 'landlord-portfolio-cover', 'service', 'Landlord Portfolio Cover', NULL, NULL, 1, 1),
(600, 60, 'listing-photo-packages', 'service', 'Listing Photo Packages', NULL, NULL, 1, 1),
(610, 61, 'walkthrough-video-tours', 'service', 'Walkthrough Video Tours', NULL, NULL, 1, 1),
(620, 62, 'home-staging-consultations', 'service', 'Home Staging Consultations', NULL, NULL, 1, 1),
(630, 63, 'drone-footage', 'service', 'Drone Footage', NULL, NULL, 1, 1),
(700, 70, 'residential-alteration-design', 'service', 'Residential Alteration Design', NULL, NULL, 1, 1),
(701, 70, 'new-home-design', 'service', 'New Home Design', NULL, NULL, 1, 2),
(702, 70, 'building-plan-submissions', 'service', 'Building Plan Submissions', NULL, NULL, 1, 3),
(710, 71, 'structural-assessments', 'service', 'Structural Assessments', NULL, NULL, 1, 1),
(720, 72, 'renovation-project-management', 'service', 'Renovation Project Management', NULL, NULL, 1, 1),
(730, 73, 'land-surveys', 'service', 'Land Surveys', NULL, NULL, 1, 1);
