-- Retired intentionally. Database Authority service startup is service-only:
-- it must not create application databases, users, grants, schema, or data.
-- Exact worktree creation owns the database and narrowly grants its account.
