export default {
  envDir: false,
  test: {
    name: 'database-authority-static',
    environment: 'node',
    include: [
      'server/__tests__/contract.database-production-seed-security.test.ts',
      'server/__tests__/contract.database-final-closure-authority.test.ts',
      'server/__tests__/contract.database-agent-authority.test.ts',
      'server/__tests__/contract.database-canonical-model-authority.test.ts',
      'server/__tests__/contract.database-local-lifecycle-authority.test.ts',
      'server/__tests__/contract.database-connection-path-authority.test.ts',
      'server/__tests__/contract.database-residual-utility-authority.test.ts',
      'server/__tests__/contract.developer-engine-s0-containment.test.ts',
      'server/__tests__/contract.migration-tree-authority.test.ts',
      'server/__tests__/contract.migration-execution-authority.test.ts',
      'server/__tests__/contract.property-listify-database-authority-skill.test.ts',
      'scripts/__tests__/localDbWorkflow.test.ts',
      'scripts/__tests__/databaseUtilityAuthority.test.ts',
      'scripts/__tests__/localEnvironmentAuthority.test.ts',
      'server/_core/databaseAuthority/__tests__/*.test.ts',
      'server/migrations/__tests__/migrationManifest.test.ts',
    ],
    globals: true,
    restoreMocks: true,
    clearMocks: true,
    mockReset: true,
  },
};
