import { mysqlTable, mysqlSchema, AnyMySqlColumn, int, varchar, text, timestamp, foreignKey, mysqlEnum } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const agencies = mysqlTable("agencies", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	slug: varchar({ length: 255 }).notNull(),
	description: text(),
	logo: text(),
	website: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	address: text(),
	city: varchar({ length: 100 }),
	province: varchar({ length: 100 }),
	subscriptionPlan: varchar({ length: 50 }).default('free').notNull(),
	subscriptionStatus: varchar({ length: 30 }).default('trial').notNull(),
	subscriptionExpiry: timestamp({ mode: 'string' }),
	isVerified: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const agencyBranding = mysqlTable("agency_branding", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	primaryColor: varchar({ length: 7 }),
	secondaryColor: varchar({ length: 7 }),
	accentColor: varchar({ length: 7 }),
	logoUrl: text(),
	faviconUrl: text(),
	customDomain: varchar({ length: 255 }),
	subdomain: varchar({ length: 63 }),
	companyName: varchar({ length: 255 }),
	tagline: varchar({ length: 255 }),
	customCss: text(),
	metaTitle: varchar({ length: 255 }),
	metaDescription: text(),
	supportEmail: varchar({ length: 320 }),
	supportPhone: varchar({ length: 50 }),
	socialLinks: text(),
	isEnabled: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const agencyJoinRequests = mysqlTable("agency_join_requests", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	status: mysqlEnum(['pending','approved','rejected']).default('pending').notNull(),
	message: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	reviewedBy: int().references(() => users.id, { onDelete: "set null" } ),
	reviewedAt: timestamp({ mode: 'string' }),
});

export const agencySubscriptions = mysqlTable("agency_subscriptions", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	planId: int().references(() => plans.id, { onDelete: "set null" } ),
	stripeSubscriptionId: varchar({ length: 100 }),
	stripeCustomerId: varchar({ length: 100 }).notNull(),
	stripePriceId: varchar({ length: 100 }),
	status: mysqlEnum(['incomplete','incomplete_expired','trialing','active','past_due','canceled','unpaid']).default('incomplete').notNull(),
	currentPeriodStart: timestamp({ mode: 'string' }),
	currentPeriodEnd: timestamp({ mode: 'string' }),
	trialEnd: timestamp({ mode: 'string' }),
	cancelAtPeriodEnd: int().notNull(),
	canceledAt: timestamp({ mode: 'string' }),
	endedAt: timestamp({ mode: 'string' }),
	metadata: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const agentCoverageAreas = mysqlTable("agent_coverage_areas", {
	id: int().autoincrement().notNull(),
	agentId: int().notNull().references(() => agents.id, { onDelete: "cascade" } ),
	areaName: varchar({ length: 255 }).notNull(),
	areaType: mysqlEnum(['province','city','suburb','custom_polygon']).notNull(),
	areaData: text().notNull(),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const agents = mysqlTable("agents", {
	id: int().autoincrement().notNull(),
	userId: int().references(() => users.id, { onDelete: "cascade" } ),
	agencyId: int().references(() => agencies.id, { onDelete: "set null" } ),
	firstName: varchar({ length: 100 }).notNull(),
	lastName: varchar({ length: 100 }).notNull(),
	displayName: varchar({ length: 200 }),
	bio: text(),
	profileImage: text(),
	phone: varchar({ length: 50 }),
	email: varchar({ length: 320 }),
	whatsapp: varchar({ length: 50 }),
	specialization: text(),
	role: mysqlEnum(['agent','principal_agent','broker']).default('agent').notNull(),
	licenseNumber: varchar({ length: 100 }),
	yearsExperience: int(),
	areasServed: text(),
	languages: text(),
	rating: int(),
	reviewCount: int(),
	totalSales: int(),
	isVerified: int().notNull(),
	isFeatured: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const analyticsAggregations = mysqlTable("analytics_aggregations", {
	id: int().autoincrement().notNull(),
	aggregationType: mysqlEnum(['daily','weekly','monthly']).notNull(),
	aggregationDate: varchar({ length: 10 }).notNull(),
	suburbId: int().references(() => suburbs.id, { onDelete: "cascade" } ),
	cityId: int().references(() => cities.id, { onDelete: "cascade" } ),
	provinceId: int().references(() => provinces.id, { onDelete: "cascade" } ),
	propertyType: varchar({ length: 50 }),
	listingType: varchar({ length: 50 }),
	totalProperties: int(),
	activeListings: int(),
	avgPrice: int(),
	medianPrice: int(),
	minPrice: int(),
	maxPrice: int(),
	pricePerSqmAvg: int(),
	totalViews: int(),
	totalSaves: int(),
	totalContacts: int(),
	uniqueVisitors: int(),
	newListings: int(),
	soldProperties: int(),
	rentedProperties: int(),
	avgDaysOnMarket: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const auditLogs = mysqlTable("audit_logs", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	action: varchar({ length: 100 }).notNull(),
	targetType: varchar({ length: 50 }),
	targetId: int(),
	metadata: text(),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const cities = mysqlTable("cities", {
	id: int().autoincrement().notNull(),
	provinceId: int().notNull().references(() => provinces.id, { onDelete: "cascade" } ),
	name: varchar({ length: 150 }).notNull(),
	latitude: varchar({ length: 20 }),
	longitude: varchar({ length: 21 }),
	isMetro: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const cityPriceAnalytics = mysqlTable("city_price_analytics", {
	id: int().autoincrement().notNull(),
	cityId: int().notNull().references(() => cities.id, { onDelete: "cascade" } ),
	provinceId: int().notNull().references(() => provinces.id, { onDelete: "cascade" } ),
	currentAvgPrice: int(),
	currentMedianPrice: int(),
	currentMinPrice: int(),
	currentMaxPrice: int(),
	currentPriceCount: int(),
	sixMonthGrowthPercent: int(),
	threeMonthGrowthPercent: int(),
	oneMonthGrowthPercent: int(),
	totalProperties: int(),
	activeListings: int(),
	averageDaysOnMarket: int(),
	luxurySegmentPercent: int(),
	midRangePercent: int(),
	affordablePercent: int(),
	lastUpdated: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const commissions = mysqlTable("commissions", {
	id: int().autoincrement().notNull(),
	agentId: int().notNull().references(() => agents.id, { onDelete: "cascade" } ),
	propertyId: int().references(() => properties.id, { onDelete: "set null" } ),
	leadId: int().references(() => leads.id, { onDelete: "set null" } ),
	amount: int().notNull(),
	percentage: int(),
	status: mysqlEnum(['pending','approved','paid','cancelled']).default('pending').notNull(),
	transactionType: mysqlEnum(['sale','rent','referral','other']).default('sale').notNull(),
	description: text(),
	payoutDate: timestamp({ mode: 'string' }),
	paymentReference: varchar({ length: 100 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

// Listing Wizard Tables
export const listings = mysqlTable("listings", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	action: mysqlEnum(['sell','rent','auction']).notNull(),
	propertyType: mysqlEnum(['apartment','house','farm','land','commercial','shared_living']).notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text().notNull(),
	pricing: text(), // JSON field for pricing details
	propertyDetails: text(), // JSON field for property-specific details
	address: text().notNull(),
	latitude: varchar({ length: 20 }).notNull(),
	longitude: varchar({ length: 21 }).notNull(),
	city: varchar({ length: 100 }).notNull(),
	suburb: varchar({ length: 100 }),
	province: varchar({ length: 100 }).notNull(),
	postalCode: varchar({ length: 10 }),
	placeId: varchar({ length: 255 }), // Google Maps Place ID
	slug: varchar({ length: 255 }).notNull(),
	status: mysqlEnum(['draft','pending_review','approved','published','rejected','archived']).default('draft').notNull(),
	approvalStatus: mysqlEnum(['pending','reviewing','approved','rejected']).default('pending').notNull(),
	approvalNotes: text(),
	rejectionReason: text(),
	publishedAt: timestamp({ mode: 'string' }),
	canonicalUrl: varchar({ length: 500 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const listingMedia = mysqlTable("listing_media", {
	id: int().autoincrement().notNull(),
	listingId: int().notNull().references(() => listings.id, { onDelete: "cascade" } ),
	url: text().notNull(),
	thumbnailUrl: text(),
	type: mysqlEnum(['image','video','floorplan','pdf']).notNull(),
	fileName: varchar({ length: 255 }),
	fileSize: int(),
	width: int(),
	height: int(),
	duration: int(), // for videos
	orientation: mysqlEnum(['vertical','horizontal','square']),
	displayOrder: int().notNull(),
	isPrimary: int().default(0).notNull(),
	processingStatus: mysqlEnum(['pending','processing','completed','failed']).default('pending').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const listingAnalytics = mysqlTable("listing_analytics", {
	id: int().autoincrement().notNull(),
	listingId: int().notNull().references(() => listings.id, { onDelete: "cascade" } ),
	totalViews: int().default(0).notNull(),
	uniqueVisitors: int().default(0).notNull(),
	totalLeads: int().default(0).notNull(),
	contactFormLeads: int().default(0).notNull(),
	whatsappClicks: int().default(0).notNull(),
	phoneReveals: int().default(0).notNull(),
	bookingViewingRequests: int().default(0).notNull(),
	totalFavorites: int().default(0).notNull(),
	totalShares: int().default(0).notNull(),
	conversionRate: int().default(0).notNull(),
	viewsByDay: text(), // JSON field for daily view counts
	trafficSources: text(), // JSON field for traffic source data
	lastUpdated: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const listingLeads = mysqlTable("listing_leads", {
	id: int().autoincrement().notNull(),
	listingId: int().notNull().references(() => listings.id, { onDelete: "cascade" } ),
	name: varchar({ length: 255 }).notNull(),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	message: text(),
	leadType: mysqlEnum(['contact_form','whatsapp_click','phone_reveal','book_viewing','make_offer','request_info']).notNull(),
	source: varchar({ length: 100 }),
	status: mysqlEnum(['new','contacted','qualified','viewing_scheduled','offer_made','converted','lost']).default('new').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const listingViewings = mysqlTable("listing_viewings", {
	id: int().autoincrement().notNull(),
	listingId: int().notNull().references(() => listings.id, { onDelete: "cascade" } ),
	prospectId: int().references(() => prospects.id, { onDelete: "cascade" } ),
	agentId: int().references(() => agents.id, { onDelete: "cascade" } ),
	scheduledAt: timestamp({ mode: 'string' }).notNull(),
	durationMinutes: int().default(30).notNull(),
	status: mysqlEnum(['scheduled','confirmed','completed','cancelled','no_show']).default('scheduled').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const listingApprovalQueue = mysqlTable("listing_approval_queue", {
	id: int().autoincrement().notNull(),
	listingId: int().notNull().references(() => listings.id, { onDelete: "cascade" } ),
	submittedBy: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	submittedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	status: mysqlEnum(['pending','reviewing','approved','rejected']).default('pending').notNull(),
	priority: mysqlEnum(['low','normal','high','urgent']).default('normal').notNull(),
	reviewedBy: int().references(() => users.id, { onDelete: "set null" } ),
	reviewedAt: timestamp({ mode: 'string' }),
	reviewNotes: text(),
	rejectionReason: text(),
});

export const coupons = mysqlTable("coupons", {
	id: int().autoincrement().notNull(),
	code: varchar({ length: 50 }).notNull(),
	stripeCouponId: varchar({ length: 100 }),
	name: varchar({ length: 100 }),
	description: text(),
	discountType: mysqlEnum(['amount','percent']).default('percent').notNull(),
	discountAmount: int(),
	maxRedemptions: int(),
	redemptionsUsed: int().notNull(),
	validFrom: timestamp({ mode: 'string' }),
	validUntil: timestamp({ mode: 'string' }),
	isActive: int().default(1).notNull(),
	appliesToPlans: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const developers = mysqlTable("developers", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	logo: text(),
	website: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	address: text(),
	city: varchar({ length: 100 }),
	province: varchar({ length: 100 }),
	category: mysqlEnum(['residential','commercial','mixed_use','industrial']).default('residential').notNull(),
	establishedYear: int(),
	totalProjects: int(),
	rating: int(),
	reviewCount: int(),
	isVerified: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const developments = mysqlTable("developments", {
	id: int().autoincrement().notNull(),
	developerId: int().references(() => developers.id, { onDelete: "cascade" } ),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	developmentType: mysqlEnum(['residential','commercial','mixed_use','estate','complex']).notNull(),
	status: mysqlEnum(['planning','under_construction','completed','coming_soon']).default('planning').notNull(),
	address: text(),
	city: varchar({ length: 100 }).notNull(),
	province: varchar({ length: 100 }).notNull(),
	latitude: varchar({ length: 50 }),
	longitude: varchar({ length: 50 }),
	totalUnits: int(),
	availableUnits: int(),
	priceFrom: int(),
	priceTo: int(),
	amenities: text(),
	images: text(),
	videos: text(),
	completionDate: timestamp({ mode: 'string' }),
	isFeatured: int().notNull(),
	views: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const emailTemplates = mysqlTable("email_templates", {
	id: int().autoincrement().notNull(),
	templateKey: varchar({ length: 100 }).notNull(),
	subject: varchar({ length: 255 }).notNull(),
	htmlContent: text().notNull(),
	textContent: text(),
	agencyId: int().references(() => agencies.id, { onDelete: "cascade" } ),
	isActive: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const exploreVideos = mysqlTable("exploreVideos", {
	id: int().autoincrement().notNull(),
	agentId: int().references(() => agents.id, { onDelete: "cascade" } ),
	propertyId: int().references(() => properties.id, { onDelete: "set null" } ),
	developmentId: int().references(() => developments.id, { onDelete: "set null" } ),
	title: varchar({ length: 255 }).notNull(),
	description: text(),
	videoUrl: text().notNull(),
	thumbnailUrl: text(),
	duration: int(),
	views: int().notNull(),
	likes: int().notNull(),
	shares: int().notNull(),
	isPublished: int().default(1).notNull(),
	isFeatured: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const favorites = mysqlTable("favorites", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const invitations = mysqlTable("invitations", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	invitedBy: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	email: varchar({ length: 320 }).notNull(),
	role: varchar({ length: 50 }).default('agent').notNull(),
	token: varchar({ length: 255 }).notNull(),
	status: mysqlEnum(['pending','accepted','expired','cancelled']).default('pending').notNull(),
	expiresAt: timestamp({ mode: 'string' }).notNull(),
	acceptedAt: timestamp({ mode: 'string' }),
	acceptedBy: int().references(() => users.id, { onDelete: "set null" } ),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const invites = mysqlTable("invites", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	email: varchar({ length: 255 }).notNull(),
	token: varchar({ length: 255 }).notNull(),
	role: varchar({ length: 30 }).default('agent'),
	expiresAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	used: int().notNull(),
	usedAt: timestamp({ mode: 'string' }),
	usedBy: int().references(() => users.id, { onDelete: "set null" } ),
});

export const invoices = mysqlTable("invoices", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	subscriptionId: int().references(() => agencySubscriptions.id, { onDelete: "set null" } ),
	stripeInvoiceId: varchar({ length: 100 }),
	stripeCustomerId: varchar({ length: 100 }),
	amount: int().notNull(),
	currency: varchar({ length: 3 }).default('ZAR').notNull(),
	status: mysqlEnum(['draft','open','paid','void','uncollectible']).default('draft').notNull(),
	invoicePdf: text(),
	hostedInvoiceUrl: text(),
	invoiceNumber: varchar({ length: 50 }),
	description: text(),
	billingReason: mysqlEnum(['subscription_cycle','subscription_create','subscription_update','subscription_finalize','manual']).default('subscription_cycle').notNull(),
	periodStart: timestamp({ mode: 'string' }),
	periodEnd: timestamp({ mode: 'string' }),
	paidAt: timestamp({ mode: 'string' }),
	dueDate: timestamp({ mode: 'string' }),
	metadata: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const leadActivities = mysqlTable("lead_activities", {
	id: int().autoincrement().notNull(),
	leadId: int().notNull().references(() => leads.id, { onDelete: "cascade" } ),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	activityType: mysqlEnum(['call','email','meeting','note','status_change','viewing_scheduled','offer_sent']).notNull(),
	description: text(),
	metadata: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const leads = mysqlTable("leads", {
	id: int().autoincrement().notNull(),
	propertyId: int().references(() => properties.id, { onDelete: "set null" } ),
	developmentId: int().references(() => developments.id, { onDelete: "set null" } ),
	agencyId: int().references(() => agencies.id, { onDelete: "set null" } ),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	name: varchar({ length: 200 }).notNull(),
	email: varchar({ length: 320 }).notNull(),
	phone: varchar({ length: 50 }),
	message: text(),
	leadType: mysqlEnum(['inquiry','viewing_request','offer','callback']).default('inquiry').notNull(),
	status: mysqlEnum(['new','contacted','qualified','converted','closed','viewing_scheduled','offer_sent','lost']).default('new').notNull(),
	source: varchar({ length: 100 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	nextFollowUp: timestamp({ mode: 'string' }),
	lastContactedAt: timestamp({ mode: 'string' }),
	notes: text(),
});

export const locationSearchCache = mysqlTable("location_search_cache", {
	id: int().autoincrement().notNull(),
	searchQuery: varchar({ length: 255 }).notNull(),
	searchType: mysqlEnum(['province','city','suburb','address','all']).notNull(),
	resultsJson: text().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	expiresAt: timestamp({ mode: 'string' }).notNull(),
});

export const locations = mysqlTable("locations", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	slug: varchar({ length: 200 }).notNull(),
	type: mysqlEnum(['province','city','suburb','neighborhood']).notNull(),
	parentId: int(),
	description: text(),
	latitude: varchar({ length: 50 }),
	longitude: varchar({ length: 50 }),
	propertyCount: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const marketInsightsCache = mysqlTable("market_insights_cache", {
	id: int().autoincrement().notNull(),
	cacheKey: varchar({ length: 255 }).notNull(),
	cacheData: text().notNull(),
	cacheType: mysqlEnum(['suburb_heatmap','city_trends','popular_areas','price_predictions','user_recommendations']).notNull(),
	expiresAt: timestamp({ mode: 'string' }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const notifications = mysqlTable("notifications", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	type: mysqlEnum(['lead_assigned','offer_received','showing_scheduled','system_alert']).notNull(),
	title: varchar({ length: 255 }).notNull(),
	content: text().notNull(),
	data: text(),
	isRead: int().notNull(),
	readAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const offers = mysqlTable("offers", {
	id: int().autoincrement().notNull(),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	leadId: int().references(() => leads.id, { onDelete: "set null" } ),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	buyerName: varchar({ length: 200 }).notNull(),
	buyerEmail: varchar({ length: 320 }),
	buyerPhone: varchar({ length: 50 }),
	offerAmount: int().notNull(),
	status: mysqlEnum(['pending','accepted','rejected','countered','withdrawn']).default('pending').notNull(),
	conditions: text(),
	expiresAt: timestamp({ mode: 'string' }),
	respondedAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const paymentMethods = mysqlTable("payment_methods", {
	id: int().autoincrement().notNull(),
	agencyId: int().notNull().references(() => agencies.id, { onDelete: "cascade" } ),
	stripePaymentMethodId: varchar({ length: 100 }),
	type: mysqlEnum(['card','bank_account']).default('card').notNull(),
	cardBrand: varchar({ length: 20 }),
	cardLast4: varchar({ length: 4 }),
	cardExpMonth: int(),
	cardExpYear: int(),
	bankName: varchar({ length: 100 }),
	bankLast4: varchar({ length: 4 }),
	isDefault: int().notNull(),
	isActive: int().default(1).notNull(),
	metadata: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const plans = mysqlTable("plans", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 100 }).notNull(),
	displayName: varchar({ length: 100 }).notNull(),
	description: text(),
	price: int().notNull(),
	currency: varchar({ length: 3 }).default('ZAR').notNull(),
	interval: mysqlEnum(['month','year']).default('month').notNull(),
	stripePriceId: varchar({ length: 100 }),
	features: text(),
	limits: text(),
	isActive: int().default(1).notNull(),
	isPopular: int().notNull(),
	sortOrder: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const platformSettings = mysqlTable("platform_settings", {
	id: int().autoincrement().notNull(),
	key: varchar({ length: 100 }).notNull(),
	value: text().notNull(),
	description: text(),
	category: mysqlEnum(['pricing','features','notifications','limits','other']).default('other').notNull(),
	isPublic: int().notNull(),
	updatedBy: int().references(() => users.id, { onDelete: "set null" } ),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const priceAnalytics = mysqlTable("price_analytics", {
	id: int().autoincrement().notNull(),
	locationId: int().notNull(),
	locationType: mysqlEnum(['suburb','city','province']).notNull(),
	currentAvgPrice: int(),
	currentMedianPrice: int(),
	currentMinPrice: int(),
	currentMaxPrice: int(),
	currentPriceCount: int(),
	oneMonthGrowthPercent: int(),
	threeMonthGrowthPercent: int(),
	sixMonthGrowthPercent: int(),
	oneYearGrowthPercent: int(),
	luxurySegmentPercent: int(),
	midRangePercent: int(),
	affordablePercent: int(),
	avgDaysOnMarket: int(),
	newListingsMonthly: int(),
	soldPropertiesMonthly: int(),
	trendingDirection: mysqlEnum(['up','down','stable']).default('stable').notNull(),
	trendConfidence: int(),
	totalProperties: int(),
	activeListings: int(),
	userInteractions: int(),
	priceVolatility: int(),
	marketMomentum: int(),
	investmentScore: int(),
	lastUpdated: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const priceHistory = mysqlTable("price_history", {
	id: int().autoincrement().notNull(),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	suburbId: int(),
	cityId: int(),
	provinceId: int(),
	price: int().notNull(),
	pricePerSqm: int(),
	propertyType: mysqlEnum(['apartment','house','villa','plot','commercial','townhouse','cluster_home','farm','shared_living']).notNull(),
	listingType: mysqlEnum(['sale','rent','rent_to_buy','auction','shared_living']).notNull(),
	recordedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	source: mysqlEnum(['new_listing','price_change','sold','rented','market_update']).default('market_update').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const pricePredictions = mysqlTable("price_predictions", {
	id: int().autoincrement().notNull(),
	propertyId: int().references(() => properties.id, { onDelete: "cascade" } ),
	suburbId: int().references(() => suburbs.id, { onDelete: "cascade" } ),
	cityId: int().references(() => cities.id, { onDelete: "cascade" } ),
	provinceId: int().references(() => provinces.id, { onDelete: "cascade" } ),
	predictedPrice: int().notNull(),
	predictedPriceRangeMin: int(),
	predictedPriceRangeMax: int(),
	confidenceScore: int(),
	modelVersion: varchar({ length: 50 }),
	modelFeatures: text(),
	trainingDataSize: int(),
	actualPrice: int(),
	predictionError: int(),
	predictionAccuracy: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	validatedAt: timestamp({ mode: 'string' }),
});

export const properties = mysqlTable("properties", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 255 }).notNull(),
	description: text().notNull(),
	propertyType: mysqlEnum(['apartment','house','villa','plot','commercial','townhouse','cluster_home','farm','shared_living']).notNull(),
	listingType: mysqlEnum(['sale','rent','rent_to_buy','auction','shared_living']).notNull(),
	transactionType: mysqlEnum(['sale','rent','rent_to_buy','auction']).default('sale').notNull(),
	price: int().notNull(),
	bedrooms: int(),
	bathrooms: int(),
	area: int().notNull(),
	address: text().notNull(),
	city: varchar({ length: 100 }).notNull(),
	province: varchar({ length: 100 }).notNull(),
	zipCode: varchar({ length: 20 }),
	latitude: varchar({ length: 50 }),
	longitude: varchar({ length: 50 }),
	provinceId: int().references(() => provinces.id, { onDelete: "set null" } ),
	cityId: int().references(() => cities.id, { onDelete: "set null" } ),
	suburbId: int().references(() => suburbs.id, { onDelete: "set null" } ),
	locationText: text(),
	placeId: varchar({ length: 255 }),
	amenities: text(),
	yearBuilt: int(),
	status: mysqlEnum(['available','sold','rented','pending','draft','published','archived']).default('available').notNull(),
	featured: int().notNull(),
	views: int().notNull(),
	enquiries: int().notNull(),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	developmentId: int().references(() => developments.id, { onDelete: "set null" } ),
	ownerId: int().notNull().references(() => users.id),
	propertySettings: text(),
	videoUrl: text(),
	virtualTourUrl: text(),
	levies: int(),
	ratesAndTaxes: int(),
	mainImage: varchar({ length: 1024 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const propertyImages = mysqlTable("propertyImages", {
	id: int().autoincrement().notNull(),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	imageUrl: text().notNull(),
	isPrimary: int().notNull(),
	displayOrder: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const propertySimilarityIndex = mysqlTable("property_similarity_index", {
	id: int().autoincrement().notNull(),
	propertyId1: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	propertyId2: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	locationSimilarity: int(),
	priceSimilarity: int(),
	typeSimilarity: int(),
	featureSimilarity: int(),
	overallSimilarity: int(),
	similarityReason: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const prospectFavorites = mysqlTable("prospect_favorites", {
	id: int().autoincrement().notNull(),
	prospectId: int().notNull().references(() => prospects.id, { onDelete: "cascade" } ),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const prospects = mysqlTable("prospects", {
	id: int().autoincrement().notNull(),
	sessionId: varchar({ length: 255 }).notNull(),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	income: int(),
	incomeRange: mysqlEnum(['under_15k','15k_25k','25k_50k','50k_100k','over_100k']),
	employmentStatus: mysqlEnum(['employed','self_employed','business_owner','student','retired','unemployed']),
	combinedIncome: int(),
	monthlyExpenses: int(),
	monthlyDebts: int(),
	dependents: int(),
	savingsDeposit: int(),
	creditScore: int(),
	hasCreditConsent: int(),
	buyabilityScore: mysqlEnum(['low','medium','high']),
	affordabilityMin: int(),
	affordabilityMax: int(),
	monthlyPaymentCapacity: int(),
	profileProgress: int(),
	badges: text(),
	lastActivity: timestamp({ mode: 'string' }),
	preferredPropertyType: mysqlEnum(['apartment','house','villa','plot','commercial','townhouse','cluster_home','farm','shared_living']),
	preferredLocation: varchar({ length: 100 }),
	maxCommuteTime: int(),
	ipAddress: varchar({ length: 45 }),
	userAgent: text(),
	referrer: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const provinces = mysqlTable("provinces", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 100 }).notNull(),
	code: varchar({ length: 10 }).notNull(),
	latitude: varchar({ length: 20 }),
	longitude: varchar({ length: 21 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const recentlyViewed = mysqlTable("recently_viewed", {
	id: int().autoincrement().notNull(),
	prospectId: int().notNull().references(() => prospects.id, { onDelete: "cascade" } ),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	viewedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const reviews = mysqlTable("reviews", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	reviewType: mysqlEnum(['agent','developer','property']).notNull(),
	targetId: int().notNull(),
	rating: int().notNull(),
	title: varchar({ length: 255 }),
	comment: text(),
	isVerified: int().notNull(),
	isPublished: int().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const scheduledViewings = mysqlTable("scheduled_viewings", {
	id: int().autoincrement().notNull(),
	prospectId: int().notNull().references(() => prospects.id, { onDelete: "cascade" } ),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	scheduledAt: timestamp({ mode: 'string' }).notNull(),
	status: mysqlEnum(['scheduled','confirmed','completed','cancelled','no_show']).default('scheduled').notNull(),
	notes: text(),
	prospectName: varchar({ length: 200 }),
	prospectEmail: varchar({ length: 320 }),
	prospectPhone: varchar({ length: 50 }),
	notificationSent: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const services = mysqlTable("services", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	category: mysqlEnum(['home_loan','insurance','interior_design','legal','moving','other']).notNull(),
	description: text(),
	logo: text(),
	website: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	commissionRate: int(),
	isActive: int().default(1).notNull(),
	isFeatured: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const showings = mysqlTable("showings", {
	id: int().autoincrement().notNull(),
	propertyId: int().notNull().references(() => properties.id, { onDelete: "cascade" } ),
	leadId: int().references(() => leads.id, { onDelete: "set null" } ),
	agentId: int().references(() => agents.id, { onDelete: "set null" } ),
	scheduledAt: timestamp({ mode: 'string' }).notNull(),
	status: mysqlEnum(['requested','confirmed','completed','cancelled']).default('requested').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const suburbPriceAnalytics = mysqlTable("suburb_price_analytics", {
	id: int().autoincrement().notNull(),
	suburbId: int().notNull().references(() => suburbs.id, { onDelete: "cascade" } ),
	cityId: int().notNull().references(() => cities.id, { onDelete: "cascade" } ),
	provinceId: int().notNull().references(() => provinces.id, { onDelete: "cascade" } ),
	currentAvgPrice: int(),
	currentMedianPrice: int(),
	currentMinPrice: int(),
	currentMaxPrice: int(),
	currentPriceCount: int(),
	lastMonthAvgPrice: int(),
	lastMonthMedianPrice: int(),
	lastMonthPriceCount: int(),
	sixMonthGrowthPercent: int(),
	threeMonthGrowthPercent: int(),
	oneMonthGrowthPercent: int(),
	trendingDirection: mysqlEnum(['up','down','stable']).default('stable').notNull(),
	trendConfidence: int(),
	lastUpdated: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const suburbs = mysqlTable("suburbs", {
	id: int().autoincrement().notNull(),
	cityId: int().notNull().references(() => cities.id, { onDelete: "cascade" } ),
	name: varchar({ length: 200 }).notNull(),
	latitude: varchar({ length: 20 }),
	longitude: varchar({ length: 21 }),
	postalCode: varchar({ length: 10 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const userBehaviorEvents = mysqlTable("user_behavior_events", {
	id: int().autoincrement().notNull(),
	userId: int().references(() => users.id, { onDelete: "set null" } ),
	sessionId: varchar({ length: 255 }).notNull(),
	eventType: mysqlEnum(['property_view','search','save_property','contact_agent','map_interaction','price_filter','location_filter','property_type_filter']).notNull(),
	eventData: text(),
	propertyId: int().references(() => properties.id, { onDelete: "set null" } ),
	suburbId: int().references(() => suburbs.id, { onDelete: "set null" } ),
	cityId: int().references(() => cities.id, { onDelete: "set null" } ),
	provinceId: int().references(() => provinces.id, { onDelete: "set null" } ),
	priceRangeMin: int(),
	priceRangeMax: int(),
	propertyType: varchar({ length: 50 }),
	listingType: varchar({ length: 50 }),
	pageUrl: varchar({ length: 500 }),
	referrer: varchar({ length: 500 }),
	userAgent: text(),
	ipAddress: varchar({ length: 45 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const userPreferences = mysqlTable("user_preferences", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	preferredPropertyTypes: text(),
	preferredPriceMin: int(),
	preferredPriceMax: int(),
	preferredBedrooms: int(),
	preferredBathrooms: int(),
	preferredPropertySize: text(),
	preferredLocations: text(),
	preferredDistance: int(),
	preferredProvices: text(),
	preferredCities: text(),
	preferredSuburbs: text(),
	requiredAmenities: text(),
	preferredAmenities: text(),
	propertyFeatures: text(),
	petFriendly: int(),
	furnished: mysqlEnum(['unfurnished','semi_furnished','fully_furnished']),
	alertFrequency: mysqlEnum(['never','instant','daily','weekly']).default('daily'),
	emailNotifications: int().default(1),
	smsNotifications: int(),
	pushNotifications: int().default(1),
	isActive: int().default(1),
	locationWeight: int().default(30),
	priceWeight: int().default(25),
	featuresWeight: int().default(25),
	sizeWeight: int().default(20),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastUsed: timestamp({ mode: 'string' }),
});

export const userRecommendations = mysqlTable("user_recommendations", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	preferredSuburbs: text(),
	preferredCities: text(),
	preferredPriceRange: text(),
	preferredPropertyTypes: text(),
	preferredListingTypes: text(),
	recommendedSuburbs: text(),
	recommendedProperties: text(),
	recommendedSimilarUsers: text(),
	recommendationClickCount: int(),
	recommendationConversionCount: int(),
	lastRecommendationUpdate: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	openId: varchar({ length: 64 }),
	email: varchar({ length: 320 }),
	passwordHash: varchar({ length: 255 }),
	name: text(),
	firstName: varchar({ length: 100 }),
	lastName: varchar({ length: 100 }),
	phone: varchar({ length: 30 }),
	loginMethod: varchar({ length: 64 }),
	emailVerified: int().notNull(),
	role: mysqlEnum(['visitor','agent','agency_admin','property_developer','super_admin']).default('visitor').notNull(),
	agencyId: int().references(() => agencies.id, { onDelete: "set null" } ),
	isSubaccount: int().notNull(),
	passwordResetToken: varchar({ length: 255 }),
	passwordResetTokenExpiresAt: timestamp({ mode: 'string' }),
	emailVerificationToken: varchar({ length: 255 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const videoLikes = mysqlTable("videoLikes", {
	id: int().autoincrement().notNull(),
	videoId: int().notNull().references(() => videos.id, { onDelete: "cascade" } ),
	userId: int().notNull().references(() => users.id, { onDelete: "cascade" } ),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const videos = mysqlTable("videos", {
	id: int().autoincrement().notNull(),
	agentId: int().references(() => agents.id, { onDelete: "cascade" } ),
	propertyId: int().references(() => properties.id, { onDelete: "set null" } ),
	developmentId: int().references(() => developments.id, { onDelete: "set null" } ),
	videoUrl: text().notNull(),
	caption: text(),
	type: mysqlEnum(['listing','content']).default('content').notNull(),
	duration: int(),
	views: int().notNull(),
	likes: int().notNull(),
	shares: int().notNull(),
	isPublished: int().default(1).notNull(),
	isFeatured: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});
