import { createHash } from 'node:crypto';

/** Restricted to the direct grants generated by the isolated CI bootstrap.
 * Unexpected role, proxy, column, global privilege or grant-option syntax fails
 * closed. This is not a general-purpose MySQL grant parser.
 */
export function assertIsolatedCiGrants(
  observed: readonly string[],
  expected: readonly string[],
  username: string,
): string {
  const normalize = (statements: readonly string[]): string[] => {
    const entries = new Set<string>();
    for (const statement of statements) {
      const match = statement
        .trim()
        .match(
          /^GRANT ([A-Z ,]+) ON (`[A-Za-z0-9_]+`|\*)\.(`[A-Za-z0-9_]+`|\*) TO ([`'])([a-z0-9_]+)\4@([`'])%\6$/,
        );
      if (!match || match[5] !== username) {
        throw new Error('Isolated CI grants contain an unsupported statement or wrong account.');
      }
      const privileges = match[1].split(',').map(value => value.trim());
      const scope = `${match[2]}.${match[3]}`;
      if (scope === '*.*' && privileges.length === 1 && privileges[0] === 'USAGE') continue;
      for (const privilege of privileges) entries.add(`${scope}:${privilege}`);
    }
    return [...entries].sort();
  };
  const actual = normalize(observed);
  const planned = normalize(expected);
  if (JSON.stringify(actual) !== JSON.stringify(planned)) {
    throw new Error('Isolated CI actual grants differ from the reviewed privilege allowlist.');
  }
  return createHash('sha256').update(JSON.stringify(actual)).digest('hex');
}
