import { Link } from 'wouter'; import { useState } from 'react'; import { trpc } from '@/lib/trpc';
export default function PlotsAndLand() {
  const params = new URLSearchParams(window.location.search);
  const handoffError = params.get('searchError');
  const [classification,setClassification]=useState<string>(params.get('classification') || '');
  const [city,setCity]=useState(params.get('city') || ''); const [province,setProvince]=useState(params.get('province') || '');
  const [minPrice,setMinPrice]=useState(params.get('minPrice') || ''); const [maxPrice,setMaxPrice]=useState(params.get('maxPrice') || '');
  const [minSize,setMinSize]=useState(params.get('minSize') || ''); const [maxSize,setMaxSize]=useState(params.get('maxSize') || '');
  const results=trpc.landPublic.search.useQuery({ classification: classification as any, city: city||undefined, province: province||undefined, minPrice: Number(minPrice)||undefined, maxPrice: Number(maxPrice)||undefined, minSize: Number(minSize)||undefined, maxSize: Number(maxSize)||undefined });
  return <main className="mx-auto max-w-6xl p-6"><h1 className="text-3xl font-semibold">Plots &amp; Land</h1><p className="mt-2 text-slate-600">Find land. Understand the land. Verify what matters.</p>{handoffError === 'unsupported-location-scope' && <p role="alert" className="mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Choose one city or province to continue into the current Land search. Suburb, multi-location, and Search Area handoff are not available yet.</p>}<div className="mt-5 grid gap-2 md:grid-cols-4"><input aria-label="City" className="rounded border p-2" placeholder="City" value={city} onChange={e=>setCity(e.target.value)} /><input aria-label="Province" className="rounded border p-2" placeholder="Province" value={province} onChange={e=>setProvince(e.target.value)} /><select aria-label="Land type" className="rounded border p-2" value={classification||''} onChange={e=>setClassification(e.target.value||'')}><option value="">All land</option><option value="residential_stand">Residential stand</option><option value="development_land">Development land</option><option value="commercial_industrial_land">Commercial / industrial land</option></select><input aria-label="Minimum price" className="rounded border p-2" type="number" placeholder="Min price" value={minPrice} onChange={e=>setMinPrice(e.target.value)} /><input aria-label="Maximum price" className="rounded border p-2" type="number" placeholder="Max price" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} /><input aria-label="Minimum size" className="rounded border p-2" type="number" placeholder="Min m²" value={minSize} onChange={e=>setMinSize(e.target.value)} /><input aria-label="Maximum size" className="rounded border p-2" type="number" placeholder="Max m²" value={maxSize} onChange={e=>setMaxSize(e.target.value)} /></div><div className="mt-6 grid gap-4 md:grid-cols-3">{results.data?.map(item=><Link key={item.listingId} href={item.href} className="rounded border p-4"><p className="font-semibold">{item.title}</p><p>{item.classification.replaceAll('_',' ')} · {Number(item.extentM2).toLocaleString()} m²</p><p>{item.city}, {item.province}</p><p>{item.intendedUse||'Land opportunity'}</p><p className="mt-2 font-medium">R {Number(item.askingPrice).toLocaleString()}</p><p className="text-sm text-slate-600">{item.passport.trustState?.replaceAll('_',' ')||'Listed with disclosures'}</p></Link>)}</div>{!results.isLoading&&!results.data?.length&&<p className="mt-8">No eligible Land listings match this search.</p>}</main> }
