import { Resend } from 'resend';
import { appendFileSync, chmodSync } from 'node:fs';
import {
  DEPLOYED_TRANSACTIONAL_EMAIL_UNAVAILABLE_MESSAGE,
  isTransactionalEmailConfigured,
  permitsLocalEmailFallback,
  resolveTransactionalEmailConfiguration,
  transactionalEmailOrigin,
} from './transactionalEmailConfig';

let resendClient: Resend | null = null;

type GovernedVerificationCapture = {
  kind: 'agent_verification' | 'agency_verification' | 'developer_verification';
  to: string;
  subject: string;
  verificationUrl: string;
  capturedAt: string;
};

/**
 * B06's joined browser proof needs the link generated by the real
 * registration path, while keeping that credential-like URL out of normal
 * test output. This sink is deliberately unavailable outside the exact
 * authority-wrapped Developer fixture. It is not a mail transport and it is
 * never consulted by deployed runtime.
 */
function governedVerificationCapture(): { path: string; kind: GovernedVerificationCapture['kind'] } | null {
  const b04Path = String(process.env.PROPERTY_LISTIFY_GOVERNED_B04_EMAIL_CAPTURE_PATH || '').trim();
  const b05Path = String(process.env.PROPERTY_LISTIFY_GOVERNED_B05_EMAIL_CAPTURE_PATH || '').trim();
  const b06Path = String(process.env.PROPERTY_LISTIFY_GOVERNED_B06_EMAIL_CAPTURE_PATH || '').trim();
  if (!b04Path && !b05Path && !b06Path) return null;
  if ([b04Path, b05Path, b06Path].filter(Boolean).length !== 1)
    throw new Error('Only one governed verification capture may be enabled.');
  const capturePath = b04Path || b05Path || b06Path;

  const authorized =
    process.env.NODE_ENV === 'test' &&
    process.env.APP_ENV === 'test' &&
    process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_FIXTURE === 'true' &&
    (b04Path
      ? !process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_PRODUCT_KEYS ||
        process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_PRODUCT_KEYS === 'agent_launch_access'
      : process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_PRODUCT_KEYS ===
        (b05Path ? 'agency_launch_access' : 'developer_launch_access')) &&
    Boolean(process.env.DATABASE_AUTHORITY_PARENT_FINGERPRINT) &&
    Boolean(process.env.DATABASE_AUTHORITY_CORRELATION_ID);
  if (!authorized) {
    throw new Error(
      'Verification capture requires the governed product-specific browser fixture.',
    );
  }
  const pathPattern = b04Path
    ? /^\/tmp\/property-listify-b04-[a-z0-9._-]+\.jsonl$/i
    : b05Path
      ? /^\/tmp\/property-listify-b05-[a-z0-9._-]+\.jsonl$/i
      : /^\/tmp\/property-listify-b06-[a-z0-9._-]+\.jsonl$/i;
  if (!pathPattern.test(capturePath)) {
    throw new Error(
      'Verification capture path must be a private product-specific /tmp JSONL artifact.',
    );
  }

  chmodSync(capturePath, 0o600);
  return { path: capturePath, kind: b04Path ? 'agent_verification' : b05Path ? 'agency_verification' : 'developer_verification' };
}

function captureGovernedVerificationMessage(
  message: Omit<GovernedVerificationCapture, 'kind' | 'capturedAt'>,
): boolean {
  const capture = governedVerificationCapture();
  if (!capture) return false;

  appendFileSync(
    capture.path,
    `${JSON.stringify({
      kind: capture.kind,
      ...message,
      capturedAt: new Date().toISOString(),
    } satisfies GovernedVerificationCapture)}\n`,
    { encoding: 'utf8', mode: 0o600 },
  );
  return true;
}

function throwUnavailableDeployedEmail(): never {
  console.error('[Email] Transactional email is unconfigured for deployed runtime', {
    runtimeEnv: process.env.APP_ENV ?? process.env.NODE_ENV ?? 'development',
  });
  throw new Error(DEPLOYED_TRANSACTIONAL_EMAIL_UNAVAILABLE_MESSAGE);
}

export function getResend() {
  if (!isTransactionalEmailConfigured()) {
    return null;
  }

  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY!);
  }

  return resendClient;
}

interface SendVerificationEmailParams {
  to: string;
  verificationToken: string;
  name?: string;
}

export async function sendVerificationEmail({
  to,
  verificationToken,
  name,
}: SendVerificationEmailParams) {
  const resend = getResend();
  if (!resend && !permitsLocalEmailFallback()) throwUnavailableDeployedEmail();
  const verificationUrl = `${transactionalEmailOrigin('api')}/api/auth/verify-email?token=${verificationToken}`;

  if (!resend) {
    const capturedInGovernedSink = captureGovernedVerificationMessage({
      to,
      subject: 'Verify your email - Property Listify',
      verificationUrl,
    });
    console.warn('[Email] RESEND_API_KEY missing — skipping sendVerificationEmail');
    // The governed B06 fixture is the only permitted token-bearing capture.
    // Ordinary local logs must never contain a credential-bearing URL.
    if (capturedInGovernedSink) {
      console.log('[Email Local Dev] Verification URL captured in governed private sink.');
    } else {
      console.log('[Email Local Dev] Verification delivery simulated.');
    }
    return { success: true, messageId: 'dev-mock-id' };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: resolveTransactionalEmailConfiguration().from,
      to: [to],
      subject: 'Verify your email - Property Listify',
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Verify Your Email</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;">
            <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              <!-- Header -->
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 600;">Property Listify</h1>
              </div>
              
              <!-- Content -->
              <div style="padding: 40px 20px;">
                <h2 style="color: #1a1a1a; margin: 0 0 20px 0; font-size: 24px;">Welcome${name ? `, ${name}` : ''}! 👋</h2>
                
                <p style="color: #4a4a4a; line-height: 1.6; margin: 0 0 20px 0; font-size: 16px;">
                  Thank you for registering with Property Listify. To complete your registration and access all features, please verify your email address.
                </p>
                
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${verificationUrl}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                    Verify Email Address
                  </a>
                </div>
                
                <p style="color: #6b7280; line-height: 1.6; margin: 20px 0 0 0; font-size: 14px;">
                  Or copy and paste this link into your browser:<br>
                  <a href="${verificationUrl}" style="color: #667eea; word-break: break-all;">${verificationUrl}</a>
                </p>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
                  <p style="color: #9ca3af; font-size: 13px; line-height: 1.6; margin: 0;">
                    If you didn't create an account with Property Listify, you can safely ignore this email.
                  </p>
                </div>
              </div>
              
              <!-- Footer -->
              <div style="background-color: #f9fafb; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                <p style="color: #9ca3af; font-size: 12px; margin: 0;">
                  © ${new Date().getFullYear()} Property Listify. All rights reserved.
                </p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    if (error) {
      console.error('[Email] Verification provider rejected the message.');
      throw new Error('Verification email delivery failed.');
    }

    console.log('[Email] Verification email sent successfully:', data?.id);
    return { success: true, messageId: data?.id };
  } catch {
    console.error('[Email] Verification email delivery failed.');
    throw new Error('Verification email delivery failed.');
  }
}

interface SendPasswordResetEmailParams {
  to: string;
  resetToken: string;
  name?: string;
}

export async function sendPasswordResetEmail({
  to,
  resetToken,
  name,
}: SendPasswordResetEmailParams) {
  const resend = getResend();
  if (!resend && !permitsLocalEmailFallback()) throwUnavailableDeployedEmail();
  const resetUrl = `${transactionalEmailOrigin('app')}/reset-password?token=${resetToken}`;

  if (!resend) {
    console.warn('[Email] RESEND_API_KEY missing — skipping sendPasswordResetEmail');
    console.log('[Email Local Dev] Password reset delivery simulated.');
    return { success: true, messageId: 'dev-mock-id' };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: resolveTransactionalEmailConfiguration().from,
      to: [to],
      subject: 'Reset your password - Property Listify',
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Reset Your Password</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;">
            <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              <!-- Header -->
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 600;">Property Listify</h1>
              </div>
              
              <!-- Content -->
              <div style="padding: 40px 20px;">
                <h2 style="color: #1a1a1a; margin: 0 0 20px 0; font-size: 24px;">Password Reset Request 🔒</h2>
                
                <p style="color: #4a4a4a; line-height: 1.6; margin: 0 0 20px 0; font-size: 16px;">
                  ${name ? `Hi ${name}, ` : ''}We received a request to reset your password. Click the button below to create a new password.
                </p>
                
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${resetUrl}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                    Reset Password
                  </a>
                </div>
                
                <p style="color: #6b7280; line-height: 1.6; margin: 20px 0 0 0; font-size: 14px;">
                  Or copy and paste this link into your browser:<br>
                  <a href="${resetUrl}" style="color: #667eea; word-break: break-all;">${resetUrl}</a>
                </p>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
                  <p style="color: #9ca3af; font-size: 13px; line-height: 1.6; margin: 0;">
                    <strong>This link will expire in 1 hour.</strong><br><br>
                    If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.
                  </p>
                </div>
              </div>
              
              <!-- Footer -->
              <div style="background-color: #f9fafb; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                <p style="color: #9ca3af; font-size: 12px; margin: 0;">
                  © ${new Date().getFullYear()} Property Listify. All rights reserved.
                </p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    if (error) {
      console.error('[Email] Password reset provider rejected the message.');
      throw new Error('Password reset email delivery failed.');
    }

    console.log('[Email] Password reset email sent successfully:', data?.id);
    return { success: true, messageId: data?.id };
  } catch {
    console.error('[Email] Password reset email delivery failed.');
    throw new Error('Password reset email delivery failed.');
  }
}
