import { Resend } from 'resend';
import { appendFileSync, chmodSync } from 'node:fs';
import { ENV } from './env';
import {
  DEPLOYED_TRANSACTIONAL_EMAIL_UNAVAILABLE_MESSAGE,
  isTransactionalEmailConfigured,
  permitsLocalEmailFallback,
} from './transactionalEmailConfig';

let resendClient: Resend | null = null;

type GovernedB06VerificationCapture = {
  kind: 'developer_verification';
  to: string;
  subject: string;
  verificationUrl: string;
  capturedAt: string;
};

/**
 * B06's joined browser proof needs the link generated by the real
 * registration path, while keeping that credential-like URL out of normal
 * test output. This sink is deliberately unavailable outside the exact
 * authority-wrapped Developer fixture. It is not a mail transport and it is
 * never consulted by deployed runtime.
 */
function governedB06VerificationCapturePath(): string | null {
  const capturePath = String(
    process.env.PROPERTY_LISTIFY_GOVERNED_B06_EMAIL_CAPTURE_PATH || '',
  ).trim();
  if (!capturePath) return null;

  const authorized =
    process.env.NODE_ENV === 'test' &&
    process.env.APP_ENV === 'test' &&
    process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_FIXTURE === 'true' &&
    process.env.PROPERTY_LISTIFY_GOVERNED_BROWSER_TEST_PRODUCT_KEYS ===
      'developer_launch_access' &&
    Boolean(process.env.DATABASE_AUTHORITY_PARENT_FINGERPRINT) &&
    Boolean(process.env.DATABASE_AUTHORITY_CORRELATION_ID);
  if (!authorized) {
    throw new Error(
      'B06 verification capture requires the governed Developer-only browser fixture.',
    );
  }
  if (!/^\/tmp\/property-listify-b06-[a-z0-9._-]+\.jsonl$/i.test(capturePath)) {
    throw new Error(
      'B06 verification capture path must be a private /tmp/property-listify-b06-*.jsonl artifact.',
    );
  }

  chmodSync(capturePath, 0o600);
  return capturePath;
}

function captureGovernedB06VerificationMessage(
  message: Omit<GovernedB06VerificationCapture, 'kind' | 'capturedAt'>,
): boolean {
  const capturePath = governedB06VerificationCapturePath();
  if (!capturePath) return false;

  appendFileSync(
    capturePath,
    `${JSON.stringify({
      kind: 'developer_verification',
      ...message,
      capturedAt: new Date().toISOString(),
    } satisfies GovernedB06VerificationCapture)}\n`,
    { encoding: 'utf8', mode: 0o600 },
  );
  return true;
}

function throwUnavailableDeployedEmail(): never {
  console.error('[Email] Transactional email is unconfigured for deployed runtime', {
    runtimeEnv: process.env.APP_ENV ?? process.env.NODE_ENV ?? 'development',
  });
  throw new Error(DEPLOYED_TRANSACTIONAL_EMAIL_UNAVAILABLE_MESSAGE);
}

export function getResend() {
  if (!isTransactionalEmailConfigured()) {
    return null;
  }

  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY!);
  }

  return resendClient;
}

interface SendVerificationEmailParams {
  to: string;
  verificationToken: string;
  name?: string;
}

export async function sendVerificationEmail({
  to,
  verificationToken,
  name,
}: SendVerificationEmailParams) {
  const rawApiBaseUrl =
    process.env.VITE_API_URL ||
    process.env.API_URL ||
    process.env.RAILWAY_PUBLIC_DOMAIN ||
    process.env.APP_URL ||
    'http://localhost:3000';
  const normalizedApiBaseUrl = rawApiBaseUrl.startsWith('http')
    ? rawApiBaseUrl.replace(/\/+$/, '')
    : `https://${rawApiBaseUrl.replace(/\/+$/, '')}`;
  const verificationUrl = `${normalizedApiBaseUrl}/api/auth/verify-email?token=${verificationToken}`;

  const resend = getResend();
  if (!resend) {
    if (!permitsLocalEmailFallback()) {
      throwUnavailableDeployedEmail();
    }
    const capturedInGovernedB06Sink = captureGovernedB06VerificationMessage({
      to,
      subject: 'Verify your email - Property Listify',
      verificationUrl,
    });
    console.warn('[Email] RESEND_API_KEY missing — skipping sendVerificationEmail');
    // Local development retains its existing inspectable URL. The B06 browser
    // fixture writes the same application-generated URL only to its private
    // capture artifact, so credential-like tokens do not enter Playwright
    // output or a shared terminal transcript.
    if (capturedInGovernedB06Sink) {
      console.log('[Email Local Dev] Verification URL captured in governed private sink.');
    } else {
      console.log('[Email Local Dev] Verification URL:', verificationUrl);
    }
    return { success: true, messageId: 'dev-mock-id' };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: ENV.resendFromEmail || 'Property Listify <onboarding@resend.dev>',
      to: [to],
      subject: 'Verify your email - Property Listify',
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Verify Your Email</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;">
            <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              <!-- Header -->
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 600;">Property Listify</h1>
              </div>
              
              <!-- Content -->
              <div style="padding: 40px 20px;">
                <h2 style="color: #1a1a1a; margin: 0 0 20px 0; font-size: 24px;">Welcome${name ? `, ${name}` : ''}! 👋</h2>
                
                <p style="color: #4a4a4a; line-height: 1.6; margin: 0 0 20px 0; font-size: 16px;">
                  Thank you for registering with Property Listify. To complete your registration and access all features, please verify your email address.
                </p>
                
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${verificationUrl}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                    Verify Email Address
                  </a>
                </div>
                
                <p style="color: #6b7280; line-height: 1.6; margin: 20px 0 0 0; font-size: 14px;">
                  Or copy and paste this link into your browser:<br>
                  <a href="${verificationUrl}" style="color: #667eea; word-break: break-all;">${verificationUrl}</a>
                </p>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
                  <p style="color: #9ca3af; font-size: 13px; line-height: 1.6; margin: 0;">
                    If you didn't create an account with Property Listify, you can safely ignore this email.
                  </p>
                </div>
              </div>
              
              <!-- Footer -->
              <div style="background-color: #f9fafb; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                <p style="color: #9ca3af; font-size: 12px; margin: 0;">
                  © ${new Date().getFullYear()} Property Listify. All rights reserved.
                </p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    if (error) {
      console.error('[Email] Failed to send verification email:', error);
      throw new Error(`Email send failed: ${error.message}`);
    }

    console.log('[Email] Verification email sent successfully:', data?.id);
    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error('[Email] Error sending verification email:', error);
    throw error;
  }
}

interface SendPasswordResetEmailParams {
  to: string;
  resetToken: string;
  name?: string;
}

export async function sendPasswordResetEmail({
  to,
  resetToken,
  name,
}: SendPasswordResetEmailParams) {
  const resetUrl = `${process.env.APP_URL || 'http://localhost:3000'}/reset-password?token=${resetToken}`;

  const resend = getResend();
  if (!resend) {
    if (!permitsLocalEmailFallback()) {
      throwUnavailableDeployedEmail();
    }
    console.warn('[Email] RESEND_API_KEY missing — skipping sendPasswordResetEmail');
    console.log('[Email Local Dev] Reset URL:', resetUrl);
    return { success: true, messageId: 'dev-mock-id' };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: ENV.resendFromEmail || 'Property Listify <onboarding@resend.dev>',
      to: [to],
      subject: 'Reset your password - Property Listify',
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Reset Your Password</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;">
            <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              <!-- Header -->
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 20px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 600;">Property Listify</h1>
              </div>
              
              <!-- Content -->
              <div style="padding: 40px 20px;">
                <h2 style="color: #1a1a1a; margin: 0 0 20px 0; font-size: 24px;">Password Reset Request 🔒</h2>
                
                <p style="color: #4a4a4a; line-height: 1.6; margin: 0 0 20px 0; font-size: 16px;">
                  ${name ? `Hi ${name}, ` : ''}We received a request to reset your password. Click the button below to create a new password.
                </p>
                
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${resetUrl}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-weight: 600; font-size: 16px;">
                    Reset Password
                  </a>
                </div>
                
                <p style="color: #6b7280; line-height: 1.6; margin: 20px 0 0 0; font-size: 14px;">
                  Or copy and paste this link into your browser:<br>
                  <a href="${resetUrl}" style="color: #667eea; word-break: break-all;">${resetUrl}</a>
                </p>
                
                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
                  <p style="color: #9ca3af; font-size: 13px; line-height: 1.6; margin: 0;">
                    <strong>This link will expire in 1 hour.</strong><br><br>
                    If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.
                  </p>
                </div>
              </div>
              
              <!-- Footer -->
              <div style="background-color: #f9fafb; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                <p style="color: #9ca3af; font-size: 12px; margin: 0;">
                  © ${new Date().getFullYear()} Property Listify. All rights reserved.
                </p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    if (error) {
      console.error('[Email] Failed to send password reset email:', error);
      throw new Error(`Email send failed: ${error.message}`);
    }

    console.log('[Email] Password reset email sent successfully:', data?.id);
    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error('[Email] Error sending password reset email:', error);
    throw error;
  }
}
