import { AlertCircle, ArrowRight, BarChart3, CalendarClock, CheckCircle2, Eye, FileText, MessageSquare, ShieldAlert } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { trpc } from '@/lib/trpc';
import { SectionTitle } from '../workspace/WorkspacePrimitives';
import type { WorkspaceContentProps } from '../workspace/types';

const money = (v: unknown) => Number(v || 0).toLocaleString('en-ZA', { style: 'currency', currency: 'ZAR', maximumFractionDigits: 0 });
const label = (value: string) => value.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase());
const signal = (row: any) => row.performance?.views > 0 && !row.performance?.enquiries ? ['Views but no enquiries', 'Ask whether the listing story or call-to-action needs work', 'attention'] : row.performance?.daysLive >= 14 && !row.performance?.views ? ['No engagement recorded', 'Start a seller review and check listing quality', 'critical'] : ['Monitoring', 'No immediate action is due', 'monitoring'];

export function AgencyListingPerformanceWorkspace(props: WorkspaceContentProps) {
  const [listingId, setListingId] = useState<number | null>(null); const [reviewOpen, setReviewOpen] = useState(false);
  const [review, setReview] = useState({ contactDate: '', contactChannel: 'call', agentAssessment: '', buyerFeedbackThemes: '', recommendation: 'review_later', recommendationReason: '', sellerDecision: 'deferred', proposedPrice: '', nextReviewAt: '', followUpNote: '' });
  const inventory = trpc.agency.getListingPerformanceQueue.useQuery();
  const detail = trpc.agency.getListingPerformance.useQuery({ listingId: listingId! }, { enabled: Boolean(listingId) }); const utils = trpc.useUtils();
  const [reportReviewId, setReportReviewId] = useState<number | null>(null);
  const saveReview = trpc.agency.recordListingPerformanceReview.useMutation({ onSuccess: () => { utils.agency.getListingPerformance.invalidate({ listingId: listingId! }); utils.agency.getListingPerformanceQueue.invalidate(); setReviewOpen(false); } });
  const requestRevision = trpc.agency.requestListingPerformancePriceRevision.useMutation({ onSuccess: data => { utils.agency.getListingPerformance.invalidate({ listingId: listingId! }); utils.agency.getListingPerformanceQueue.invalidate(); if (data.revisionListingId) props.setLocation(`/listings/create?edit=true&id=${data.revisionListingId}`); } });
  const report = trpc.agency.getListingPerformanceReport.useQuery({ reviewId: reportReviewId! }, { enabled: Boolean(reportReviewId) });
  const rows = inventory.data || []; const reviewNeeded = rows.filter((r: any) => r.actionable).length;
  return <section className="space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Listing Performance</h1><p className="mt-1 max-w-2xl text-sm text-slate-600">See what needs attention, prepare a seller discussion, and safely follow through on agreed actions.</p></div>{listingId ? <Button onClick={() => setReviewOpen(true)}>Start seller review <ArrowRight className="ml-2 h-4 w-4" /></Button> : null}</header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ShieldAlert} label="Require review" value={reviewNeeded} detail="Listings with an actionable engagement signal" /><Metric icon={CalendarClock} label="Seller updates overdue" value={rows.filter((r: any) => r.latestReview?.nextReviewAt && new Date(r.latestReview.nextReviewAt).getTime() < Date.now()).length} detail="Follow-ups that have passed their due date" /><Metric icon={Eye} label="No engagement" value={rows.filter((r: any) => r.live?.flags?.includes('no_engagement')).length} detail="Live for 14+ days without recorded views" /><Metric icon={MessageSquare} label="Conversion concern" value={rows.filter((r: any) => r.live?.flags?.includes('views_without_enquiries')).length} detail="Views recorded, but no enquiries" /></div>
    <Card className="overflow-hidden border-slate-200 shadow-sm"><CardHeader className="border-b bg-slate-50/70"><SectionTitle icon={BarChart3} title="Performance queue" eyebrow="Actionable published listings" /></CardHeader><CardContent className="p-0">{inventory.isLoading ? <State title="Loading listing performance…" /> : !rows.length ? <State title="No published listings to monitor" detail="Published inventory will appear here when it is available." /> : <div className="divide-y">{rows.map((row: any) => { const title = row.actionable ? 'Action required' : 'Monitoring'; return <button key={row.listing.id} type="button" onClick={() => { setListingId(row.listing.id); setReviewOpen(false); }} className="grid w-full gap-3 p-4 text-left transition hover:bg-slate-50 md:grid-cols-[minmax(210px,1.6fr)_repeat(3,minmax(70px,.45fr))_minmax(190px,1fr)] md:items-center"><div><div className="font-medium text-slate-900">{row.listing.title}</div><div className="mt-0.5 text-xs text-slate-500">{row.listing.city || row.listing.address} · {money(row.listing.askingPrice)}</div></div><MetricText label="Days live" value={row.live.metrics.daysLive} /><MetricText label="Views / enquiries" value={`${row.live.metrics.views} / ${row.live.metrics.enquiries}`} /><MetricText label="Owner" value={row.responsibleAgent?.name || 'Unassigned'} /><div><Badge className={row.actionable ? 'bg-amber-100 text-amber-800 hover:bg-amber-100' : 'bg-slate-100 text-slate-700 hover:bg-slate-100'}>{title}</Badge><p className="mt-1 text-xs text-slate-500">{row.reason}</p></div></button>; })}</div>}</CardContent></Card>
    {listingId && <Card className="border-slate-200 shadow-sm"><CardHeader className="border-b"><SectionTitle icon={BarChart3} title="Listing review" eyebrow="Private operational workspace" /></CardHeader><CardContent className="space-y-6 pt-5">{detail.isLoading ? <State title="Loading performance evidence…" /> : <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(detail.data?.live.metrics || {}).filter(([key]) => ['daysLive','views','enquiries','viewingRequests','completedViewings','offers'].includes(key)).map(([key,value]) => <MetricText key={key} label={label(key)} value={value === 0 && ['views','enquiries'].includes(key) ? 'No activity recorded' : String(value)} card />)}</div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><div className="flex gap-2 font-medium"><AlertCircle className="mt-0.5 h-4 w-4" />Why this needs attention</div><p className="mt-1 text-amber-900">{rows.find((row: any) => row.listing.id === listingId)?.reason || 'Review recent activity before contacting the seller.'}</p></div><p className="text-xs leading-5 text-slate-500">{detail.data?.reportBoundary}</p>{detail.data?.reviews?.map((saved: any) => <div key={saved.id} className="rounded-lg border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-slate-900">Seller decision: {label(saved.sellerDecision)}</p><p className="mt-1 text-sm text-slate-600">Recommendation: {label(saved.recommendation)}{saved.proposedPrice ? ` · proposed ${money(saved.proposedPrice)}` : ''}</p></div><Button variant="outline" onClick={() => setReportReviewId(saved.id)}><FileText className="h-4 w-4" />Seller report</Button></div>{saved.recommendation === 'change_price' && saved.sellerDecision === 'accepted' ? <RevisionHandoff review={saved} currentPrice={rows.find((row: any) => row.listing.id === listingId)?.listing.askingPrice} pending={Boolean(saved.revisionRequestedAt)} saving={requestRevision.isPending} error={requestRevision.error?.message} onRequest={() => requestRevision.mutate({ reviewId: saved.id })} /> : null}</div>)}</>}
      {reviewOpen && <ReviewForm review={review} setReview={setReview} saving={saveReview.isPending} error={saveReview.error?.message} onCancel={() => setReviewOpen(false)} onSubmit={() => saveReview.mutate({ listingId, contactDate: review.contactDate || null, contactChannel: review.contactChannel as any, agentAssessment: review.agentAssessment || null, buyerFeedbackThemes: review.buyerFeedbackThemes || null, recommendation: review.recommendation as any, recommendationReason: review.recommendationReason || null, sellerDecision: review.sellerDecision as any, proposedPrice: review.proposedPrice ? Number(review.proposedPrice) : null, nextReviewAt: review.nextReviewAt || null, followUpNote: review.followUpNote || null })} />}
    </CardContent></Card>}{reportReviewId ? <SellerReport data={report.data} loading={report.isLoading} onClose={() => setReportReviewId(null)} /> : null}
  </section>;
}
const reviewSteps = ['Seller contact', 'Listing performance', 'Agent recommendation', 'Seller decision', 'Next action and review'];

function ReviewForm({ review, setReview, saving, error, onCancel, onSubmit }: any) {
  const [step, setStep] = useState(1); const [validation, setValidation] = useState<Record<string, string>>({});
  const price = review.recommendation === 'change_price'; const followUp = ['deferred','unable_to_contact'].includes(review.sellerDecision);
  const update = (patch: Record<string, unknown>) => setReview({ ...review, ...patch });
  const validate = () => {
    const next: Record<string, string> = {};
    if (step === 1 && review.sellerDecision !== 'unable_to_contact' && !review.contactDate) next.contactDate = 'Record a contact date, or mark the seller as unable to contact.';
    if (step === 3 && price && !review.proposedPrice) next.proposedPrice = 'Enter the proposed asking price.';
    if (step === 3 && price && !review.recommendationReason.trim()) next.recommendationReason = 'Explain why a price discussion is recommended.';
    if (step === 5 && followUp && !review.nextReviewAt) next.nextReviewAt = 'Schedule the next review for this follow-up.';
    setValidation(next); return Object.keys(next).length === 0;
  };
  const advance = () => { if (validate()) setStep(current => Math.min(5, current + 1)); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (step === 5 && validate()) onSubmit(); };
  return <form className="space-y-6 border-t pt-6" onSubmit={submit}>
    <div><p className="text-sm text-slate-600">Record the conversation in five short steps. These notes are private and never change the public listing directly.</p><ol className="mt-4 grid gap-2 sm:grid-cols-5" aria-label="Seller review progress">{reviewSteps.map((title, index) => { const number = index + 1; const current = number === step; return <li key={title} aria-current={current ? 'step' : undefined} className={`rounded-md border px-3 py-2 text-sm ${current ? 'border-sky-600 bg-sky-50 text-sky-950' : number < step ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-slate-200 text-slate-500'}`}><span className="block text-xs font-medium">Step {number} of 5</span><span className="font-medium">{title}</span></li>; })}</ol></div>
    <section data-testid={`seller-review-step-${step}`} className="rounded-lg border bg-slate-50/50 p-4 pb-24"><h3 className="font-medium text-slate-900">{step}. {reviewSteps[step - 1]}</h3>
      {step === 1 ? <><p className="mb-4 mt-1 text-xs text-slate-500">Record how and when the discussion happened.</p><div className="grid gap-4 md:grid-cols-2"><Field label="Contact date"><Input aria-describedby={validation.contactDate ? 'contact-date-error' : undefined} type="datetime-local" value={review.contactDate} onChange={(e:any) => update({ contactDate:e.target.value })}/>{validation.contactDate ? <InlineError id="contact-date-error" message={validation.contactDate} /> : null}</Field><Field label="Contact channel"><select className="control" value={review.contactChannel} onChange={(e:any) => update({ contactChannel:e.target.value })}>{['call','whatsapp','email','meeting','other'].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></Field></div><label className="mt-4 flex items-start gap-2 text-sm text-slate-700"><input type="checkbox" checked={review.sellerDecision === 'unable_to_contact'} onChange={event => update({ sellerDecision: event.target.checked ? 'unable_to_contact' : 'deferred' })} /><span><span className="font-medium">Unable to contact</span><span className="block text-xs text-slate-500">This records the existing seller outcome and makes a follow-up mandatory.</span></span></label></> : null}
      {step === 2 ? <><p className="mb-4 mt-1 text-xs text-slate-500">Summarise useful feedback, not buyer identities.</p><div className="grid gap-4 md:grid-cols-2"><Field label="Buyer-feedback themes"><Textarea value={review.buyerFeedbackThemes} onChange={(e:any) => update({ buyerFeedbackThemes:e.target.value })}/></Field><Field label="Your assessment"><Textarea value={review.agentAssessment} onChange={(e:any) => update({ agentAssessment:e.target.value })}/></Field></div></> : null}
      {step === 3 ? <><p className="mb-4 mt-1 text-xs text-slate-500">Choose the clearest next intervention.</p><Field label="Recommendation"><select className="control" value={review.recommendation} onChange={(e:any) => update({ recommendation:e.target.value })}>{['keep_unchanged','improve_media','improve_description','correct_information','change_price','adjust_viewing_availability','increase_marketing','pause_listing','withdraw_listing','review_later'].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></Field>{price ? <div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Proposed asking price"><Input aria-describedby={validation.proposedPrice ? 'proposed-price-error' : undefined} type="number" value={review.proposedPrice} onChange={(e:any) => update({ proposedPrice:e.target.value })}/>{validation.proposedPrice ? <InlineError id="proposed-price-error" message={validation.proposedPrice} /> : null}</Field><Field label="Why a pricing discussion is recommended"><Textarea aria-describedby={validation.recommendationReason ? 'recommendation-reason-error' : undefined} value={review.recommendationReason} onChange={(e:any) => update({ recommendationReason:e.target.value })}/>{validation.recommendationReason ? <InlineError id="recommendation-reason-error" message={validation.recommendationReason} /> : null}</Field></div> : null}<p className="mt-4 text-xs text-amber-700">This is a recommendation only. The public price stays unchanged until the normal listing revision is approved.</p></> : null}
      {step === 4 ? <><p className="mb-4 mt-1 text-xs text-slate-500">Capture the outcome without changing the public listing.</p><Field label="Seller decision"><select className="control" value={review.sellerDecision} onChange={(e:any) => update({ sellerDecision:e.target.value })}>{['accepted','partially_accepted','rejected','deferred','unable_to_contact','unavailable'].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></Field></> : null}
      {step === 5 ? <><p className="mb-4 mt-1 text-xs text-slate-500">Confirm the agreed action before saving this private review.</p>{followUp ? <div className="grid gap-4 md:grid-cols-2"><Field label="Next review date"><Input aria-describedby={validation.nextReviewAt ? 'next-review-error' : undefined} type="datetime-local" value={review.nextReviewAt} onChange={(e:any) => update({ nextReviewAt:e.target.value })}/>{validation.nextReviewAt ? <InlineError id="next-review-error" message={validation.nextReviewAt} /> : null}</Field><Field label="Agreed next action"><Textarea value={review.followUpNote} onChange={(e:any) => update({ followUpNote:e.target.value })}/></Field></div> : <p className="rounded-md border border-slate-200 bg-white p-3 text-sm text-slate-600">No follow-up date is required for this seller decision.</p>}<ReviewSummary review={review} /></> : null}
    </section>{error ? <p className="rounded bg-rose-50 p-3 text-sm text-rose-800" role="alert">{error}</p> : null}<div className="sticky bottom-0 flex flex-wrap gap-2 border-t bg-white/95 py-4"><Button type="button" variant="outline" onClick={() => setStep(current => Math.max(1, current - 1))} disabled={step === 1}>Back</Button>{step < 5 ? <Button type="button" onClick={advance}>Next</Button> : <Button data-testid="complete-seller-review" type="submit" disabled={saving}>{saving ? 'Saving review…' : 'Complete seller review'}</Button>}<Button type="button" variant="outline" onClick={onCancel}>Cancel</Button></div></form>;
}
function InlineError({ id, message }: { id: string; message: string }) { return <p id={id} className="text-xs text-rose-700" role="alert">{message}</p>; }
function ReviewSummary({ review }: { review: any }) { return <section className="mt-5 rounded-md border border-sky-200 bg-sky-50 p-4" aria-label="Review summary"><h4 className="font-medium text-sky-950">Review summary</h4><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><SummaryRow label="Contact" value={review.sellerDecision === 'unable_to_contact' ? 'Unable to contact' : `${review.contactDate ? new Date(review.contactDate).toLocaleString('en-ZA') : 'Not recorded'} by ${label(review.contactChannel)}`} /><SummaryRow label="Recommendation" value={label(review.recommendation)} /><SummaryRow label="Seller decision" value={label(review.sellerDecision)} /><SummaryRow label="Proposed price" value={review.proposedPrice ? money(review.proposedPrice) : 'Not applicable'} />{review.nextReviewAt ? <SummaryRow label="Next review" value={new Date(review.nextReviewAt).toLocaleString('en-ZA')} /> : null}{review.followUpNote ? <SummaryRow label="Agreed next action" value={review.followUpNote} /> : null}</dl><p className="mt-4 text-xs leading-5 text-sky-900">Public-price protection: saving seller acceptance does not change the live asking price. A private listing revision and normal approval are still required.</p></section>; }
function SummaryRow({ label: rowLabel, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-sky-800">{rowLabel}</dt><dd className="mt-1 text-sky-950">{value}</dd></div>; }
function FormSection({ title, hint, children }: { title:string; hint:string; children:ReactNode }) { return <section className="rounded-lg border bg-slate-50/50 p-4"><h3 className="font-medium text-slate-900">{title}</h3><p className="mb-4 mt-1 text-xs text-slate-500">{hint}</p><div className="grid gap-4 md:grid-cols-2">{children}</div></section>; }
function Field({ label: fieldLabel, children }: { label:string; children:ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700">{fieldLabel}{children}</label>; }
function Metric({ icon: Icon, label, value, detail }: any) { return <Card className="border-slate-200 shadow-sm"><CardContent className="p-4"><Icon className="mb-3 h-4 w-4 text-slate-500"/><div className="text-xs font-medium text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold text-slate-950">{value}</div><div className="mt-1 text-xs leading-4 text-slate-500">{detail}</div></CardContent></Card>; }
function MetricText({ label, value, card }: any) { return <div className={card ? 'rounded-lg border bg-white p-3' : ''}><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-medium text-slate-900">{value}</div></div>; }
function State({ title, detail }: { title:string; detail?:string }) { return <div className="p-8 text-center"><CheckCircle2 className="mx-auto mb-3 h-6 w-6 text-slate-400"/><div className="font-medium text-slate-800">{title}</div>{detail ? <p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{detail}</p> : null}</div>; }

function RevisionHandoff({ review, currentPrice, pending, saving, error, onRequest }: any) {
  const current = Number(currentPrice || 0); const proposed = Number(review.proposedPrice || 0); const difference = proposed - current;
  const revisionState = review.canonicalRevision?.status;
  const stateCopy = revisionState === 'pending_review' ? 'The revision has been submitted for approval. The live asking price is unchanged.' : revisionState === 'rejected' ? 'The revision was rejected. Review the feedback and create a replacement draft.' : revisionState === 'archived' ? 'The revision was approved and the updated price is now live.' : pending ? 'A private revision draft has been created. Continue editing it in the Listing Engine.' : 'The seller accepted the proposed price. Create a listing revision to continue.';
  return <div className="mt-4 rounded-md border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950"><p className="font-semibold">Seller accepted a price recommendation</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><MetricText label="Current public asking price" value={money(current)} /><MetricText label="Proposed asking price" value={money(proposed)} /><MetricText label="Difference" value={`${difference < 0 ? '−' : '+'}${money(Math.abs(difference))} (${current ? ((difference / current) * 100).toFixed(1) : '0.0'}%)`} /></div><p className="mt-3 text-sky-900">{review.recommendationReason || 'No rationale recorded.'}</p><p className="mt-3 text-sky-900">{stateCopy}</p><p className="mt-3 text-xs leading-5 text-sky-800">Public-price protection: seller acceptance and the private draft do not change the live asking price. The normal Listing Engine submission and approval are still required.</p><div className="mt-4 flex flex-wrap items-center gap-2">{revisionState !== 'archived' ? <Button onClick={onRequest} disabled={saving}>{pending ? 'Continue listing revision' : saving ? 'Creating revision…' : 'Create listing revision'}</Button> : null}{pending ? <Badge className="bg-sky-100 text-sky-800 hover:bg-sky-100">{revisionState === 'pending_review' ? 'Pending approval' : 'Private revision draft'}</Badge> : null}</div>{error ? <p className="mt-2 text-xs text-rose-700">{error}</p> : null}</div>;
}

function SellerReport({ data, loading, onClose }: { data: any; loading: boolean; onClose: () => void }) {
  if (loading) return <Card><CardContent className="p-8"><State title="Preparing seller report…" /></CardContent></Card>;
  if (!data) return null;
  const metrics = data.review.metricsSnapshot || {};
  const reviewDate = data.review.contactDate || data.review.createdAt;
  return <Card className="print:shadow-none"><CardHeader className="flex-row items-center justify-between border-b print:hidden"><SectionTitle icon={FileText} title="Seller performance report" eyebrow="Saved review snapshot" /><Button variant="outline" onClick={onClose}>Close</Button></CardHeader><CardContent className="space-y-7 p-6 print:p-0"><header><p className="text-sm font-medium text-slate-500">{data.agencyName}</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Listing performance report</h2><p className="mt-2 text-sm text-slate-600">{data.listing.title} · {data.listing.address} · {data.listing.reference}</p><p className="text-sm text-slate-500">Prepared by {data.agentName} · Review date {reviewDate ? new Date(reviewDate).toLocaleDateString('en-ZA') : 'Not recorded'}</p></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricText card label="Current asking price" value={money(metrics.currentPrice ?? data.listing.currentPrice)} /><MetricText card label="Days published" value={String(metrics.daysLive ?? 0)} /><MetricText card label="Views / enquiries" value={`${metrics.views ?? 0} / ${metrics.enquiries ?? 0}`} /><MetricText card label="Viewings / offers" value={`${metrics.completedViewings ?? 0} / ${metrics.offers ?? 0}`} /></section><section className="grid gap-5 md:grid-cols-2"><ReportBlock title="Interpretation" rows={[['Performance summary', (data.review.healthFlagsSnapshot || []).length ? label((data.review.healthFlagsSnapshot || []).join(', ')) : 'No performance exception captured.'], ['Buyer-feedback themes', data.review.buyerFeedbackThemes || 'No themes recorded.'], ['Agent assessment', data.review.agentAssessment || 'No assessment recorded.']]} /><ReportBlock title="Recommendation and outcome" rows={[['Agent recommendation', label(data.review.recommendation)], ['Seller decision', label(data.review.sellerDecision)], ['Proposed price', data.review.proposedPrice ? money(data.review.proposedPrice) : 'Not applicable'], ['Next review', data.review.nextReviewAt ? new Date(data.review.nextReviewAt).toLocaleDateString('en-ZA') : 'Not scheduled'], ['Revision status', data.review.revisionRequestedAt ? 'Revision handoff created; public price remains unchanged until approval.' : 'No revision handoff created.']]} /></section><section className="border-t pt-4 text-xs leading-5 text-slate-500"><p className="font-medium text-slate-700">Important limitations</p>{data.limitations.map((item: string) => <p key={item}>{item}</p>)}</section></CardContent></Card>;
}
function ReportBlock({ title, rows }: { title: string; rows: Array<[string, string]> }) { return <section className="break-inside-avoid rounded-lg border p-4"><h3 className="font-semibold text-slate-950">{title}</h3><dl className="mt-3 space-y-3">{rows.map(([term, value]) => <div key={term}><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{term}</dt><dd className="mt-1 text-sm leading-5 text-slate-700">{value}</dd></div>)}</dl></section>; }
