import {
  LOCATION_AUTHORITY_CATALOG,
  LOCATION_AUTHORITY_CATALOG_SHA256,
  type LocationAuthorityAggregate,
} from '../../../locationAuthorityCatalog';

export const GOVERNED_RUNTIME_REFERENCE_ROWS = LOCATION_AUTHORITY_CATALOG.runtimeRows;
export const GOVERNED_RUNTIME_REFERENCE_VERSION = LOCATION_AUTHORITY_CATALOG.catalog.catalogId;
export const LOCATION_AUTHORITY_AGGREGATE: LocationAuthorityAggregate = LOCATION_AUTHORITY_CATALOG;
export const LOCATION_AUTHORITY_SOURCE_INDEX_SHA256 = LOCATION_AUTHORITY_CATALOG_SHA256;
