type CommissionTriggerStage = 'contract_signed' | 'bond_approved';
type DealStage =
  | 'viewing_scheduled'
  | 'viewing_completed'
  | 'application_submitted'
  | 'contract_signed'
  | 'bond_approved'
  | 'commission_pending'
  | 'commission_paid'
  | 'cancelled';

type EnsureCommissionInput = {
  deal: {
    id: number;
    programId: number;
    developmentId: number;
    agentId: number;
    commissionTriggerStage: CommissionTriggerStage;
    commissionBaseAmount?: number | null;
    affordabilityPurchasePrice?: number | null;
    dealAmount?: number | null;
  };
  transitionToStage: DealStage;
  actorUserId: number;
  source: string;
  deps: {
    findExistingEntry: (
      dealId: number,
      triggerStage: CommissionTriggerStage,
    ) => Promise<{ id: number } | null>;
    getProgramDefaults: (programId: number) => Promise<{
      commissionModel?: 'flat_percentage' | 'tiered_percentage' | 'fixed_amount' | 'hybrid' | null;
      defaultCommissionPercent?: number | null;
      defaultCommissionAmount?: number | null;
      currencyCode?: string | null;
    } | null>;
    insertEntry: (payload: {
      dealId: number;
      programId: number;
      developmentId: number;
      agentId: number;
      calculationBaseAmount: number;
      commissionPercent: number | null;
      commissionAmount: number;
      currency: string;
      triggerStage: CommissionTriggerStage;
      entryStatus: 'pending';
      notes: string;
      createdBy: number;
      updatedBy: number;
    }) => Promise<void>;
    setDealCommissionPending: (dealId: number) => Promise<void>;
    insertCommissionCreatedEvent: (input: {
      dealId: number;
      toStage: DealStage;
      actorUserId: number;
      metadata: Record<string, unknown>;
    }) => Promise<void>;
  };
};

const stageRank: Record<DealStage, number> = {
  viewing_scheduled: 1,
  viewing_completed: 2,
  application_submitted: 3,
  contract_signed: 4,
  bond_approved: 5,
  commission_pending: 6,
  commission_paid: 7,
  cancelled: 99,
};

function shouldCreateCommissionEntry(triggerStage: CommissionTriggerStage, nextStage: DealStage) {
  if (nextStage === 'cancelled') return false;
  return stageRank[nextStage] >= stageRank[triggerStage];
}

function resolveCalculationBaseAmount(input: EnsureCommissionInput['deal']) {
  const candidates = [
    input.commissionBaseAmount,
    input.affordabilityPurchasePrice,
    input.dealAmount,
  ];

  for (const value of candidates) {
    const normalized = Number(value ?? 0);
    if (Number.isFinite(normalized) && normalized > 0) {
      return Math.round(normalized);
    }
  }

  return 0;
}

export async function ensureCommissionEntryForDeal(input: EnsureCommissionInput) {
  const shouldCreate = shouldCreateCommissionEntry(
    input.deal.commissionTriggerStage,
    input.transitionToStage,
  );
  if (!shouldCreate) {
    return { created: false as const, reason: 'stage_not_reached' as const };
  }

  const existing = await input.deps.findExistingEntry(
    input.deal.id,
    input.deal.commissionTriggerStage,
  );
  if (existing) {
    return { created: false as const, reason: 'already_exists' as const, entryId: existing.id };
  }

  const defaults = await input.deps.getProgramDefaults(input.deal.programId);
  const model = defaults?.commissionModel ?? 'flat_percentage';
  const defaultPercent = Number(defaults?.defaultCommissionPercent ?? 0);
  const defaultAmount = Number(defaults?.defaultCommissionAmount ?? 0);
  const calculationBaseAmount = resolveCalculationBaseAmount(input.deal);
  const commissionPercent =
    model === 'fixed_amount' ? null : Number.isFinite(defaultPercent) ? defaultPercent : null;
  const commissionAmount =
    model === 'fixed_amount' || model === 'hybrid'
      ? Math.max(0, defaultAmount)
      : Math.round(Math.max(0, (calculationBaseAmount * Math.max(0, defaultPercent)) / 100));

  await input.deps.insertEntry({
    dealId: input.deal.id,
    programId: input.deal.programId,
    developmentId: input.deal.developmentId,
    agentId: input.deal.agentId,
    calculationBaseAmount,
    commissionPercent,
    commissionAmount,
    currency: defaults?.currencyCode?.trim() || 'ZAR',
    triggerStage: input.deal.commissionTriggerStage,
    entryStatus: 'pending',
    notes: `Auto-generated by ${input.source}.`,
    createdBy: input.actorUserId,
    updatedBy: input.actorUserId,
  });

  await input.deps.setDealCommissionPending(input.deal.id);
  await input.deps.insertCommissionCreatedEvent({
    dealId: input.deal.id,
    toStage: input.transitionToStage,
    actorUserId: input.actorUserId,
    metadata: {
      source: input.source,
      triggerStage: input.deal.commissionTriggerStage,
        model,
        defaultPercent,
        defaultAmount,
        calculationBaseAmount,
      },
  });

  return { created: true as const };
}
