CREATE TABLE `developer_organisations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255),
  `description` text,
  `logo` text,
  `website` varchar(255),
  `email` varchar(320),
  `phone` varchar(50),
  `address` text,
  `city` varchar(100),
  `province` varchar(100),
  `category` enum('residential','commercial','mixed_use','industrial') NOT NULL DEFAULT 'residential',
  `established_year` int,
  `track_record` text,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `rejection_reason` text,
  `approved_by` int,
  `approved_at` timestamp NULL,
  `rejected_by` int,
  `rejected_at` timestamp NULL,
  `specializations` json,
  `is_verified` tinyint NOT NULL DEFAULT 0,
  `is_trusted` tinyint NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `developer_organisations_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_developer_organisations_slug` UNIQUE (`slug`),
  CONSTRAINT `fk_developer_organisations_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_developer_organisations_rejected_by` FOREIGN KEY (`rejected_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  KEY `idx_developer_organisations_status` (`status`),
  KEY `idx_developer_organisations_name` (`name`)
);
