CREATE TABLE `land_parcels` (
  `id` int NOT NULL AUTO_INCREMENT,
  `jurisdiction_country_code` varchar(2) NOT NULL,
  `province_id` int,
  `city_id` int,
  `suburb_id` int,
  `parcel_kind` enum('erf','portion','farm','remainder','other') NOT NULL,
  `private_identifier` varchar(500) NOT NULL,
  `private_identifier_hash` varchar(64) NOT NULL,
  `extent_m2` decimal(16,2),
  `centroid_latitude` decimal(10,7),
  `centroid_longitude` decimal(10,7),
  `private_geometry` json,
  `geometry_confidence` enum('unknown','approximate','confirmed') NOT NULL DEFAULT 'unknown',
  `identity_source` enum('seller','document','authoritative_source','professional','manual') NOT NULL,
  `lifecycle_status` enum('active','retired','merged') NOT NULL DEFAULT 'active',
  `created_by_user_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_land_parcels_jurisdiction_identifier` UNIQUE (`jurisdiction_country_code`,`private_identifier_hash`),
  CONSTRAINT `fk_land_parcels_province` FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_parcels_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_parcels_suburb` FOREIGN KEY (`suburb_id`) REFERENCES `suburbs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_parcels_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  KEY `idx_land_parcels_geography` (`province_id`,`city_id`,`suburb_id`),
  KEY `idx_land_parcels_extent` (`extent_m2`)
);
