CREATE TABLE `land_evidence_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `land_asset_id` int NOT NULL,
  `parcel_id` int,
  `evidence_type` enum('mandate','identity','title_registry','parcel_survey','professional_report','planning','other') NOT NULL,
  `private_storage_key` varchar(500) NOT NULL,
  `original_file_name` varchar(255),
  `mime_type` varchar(120),
  `byte_size` int,
  `sha256` varchar(64),
  `provider_name` varchar(255),
  `custody_state` enum('received','reviewed','replaced','withdrawn','expired') NOT NULL DEFAULT 'received',
  `expires_at` timestamp NULL,
  `retention_until` timestamp NULL,
  `uploaded_by_user_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `uq_land_evidence_storage_key` UNIQUE (`private_storage_key`),
  CONSTRAINT `fk_land_evidence_asset` FOREIGN KEY (`land_asset_id`) REFERENCES `land_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_land_evidence_parcel` FOREIGN KEY (`parcel_id`) REFERENCES `land_parcels` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_evidence_uploaded_by` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  KEY `idx_land_evidence_asset_state` (`land_asset_id`,`custody_state`),
  KEY `idx_land_evidence_parcel` (`parcel_id`)
);
