CREATE TABLE `land_marketing_authorities` (
  `id` int NOT NULL AUTO_INCREMENT,
  `land_asset_id` int NOT NULL,
  `actor_type` enum('owner_direct','agent','agency','developer','other') NOT NULL,
  `agency_id` int,
  `agent_id` int,
  `authority_type` enum('sole_mandate','open_mandate','joint_mandate','owner_direct','other') NOT NULL,
  `authority_status` enum('pending','active','rejected','expired','withdrawn') NOT NULL DEFAULT 'pending',
  `effective_at` timestamp NULL,
  `expires_at` timestamp NULL,
  `review_due_at` timestamp NULL,
  `reviewer_user_id` int,
  `reviewed_at` timestamp NULL,
  `reviewer_outcome` varchar(120),
  `supporting_evidence_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_land_marketing_authority_asset` FOREIGN KEY (`land_asset_id`) REFERENCES `land_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_land_marketing_authority_agency` FOREIGN KEY (`agency_id`) REFERENCES `agencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_marketing_authority_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_marketing_authority_reviewer` FOREIGN KEY (`reviewer_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_land_marketing_authority_evidence` FOREIGN KEY (`supporting_evidence_id`) REFERENCES `land_evidence_documents` (`id`) ON DELETE SET NULL,
  KEY `idx_land_marketing_authority_asset_status` (`land_asset_id`,`authority_status`)
);
