-- Demand Engine foundation tables for campaign-driven lead routing

CREATE TABLE IF NOT EXISTS `demand_campaigns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_type` ENUM('agent', 'agency', 'developer', 'private') NOT NULL DEFAULT 'agent',
  `owner_id` INT NOT NULL,
  `created_by` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` ENUM('draft', 'active', 'paused', 'archived') NOT NULL DEFAULT 'draft',
  `source_channel` ENUM('google', 'meta', 'tiktok', 'internal', 'manual') NOT NULL DEFAULT 'manual',
  `distribution_mode` ENUM('shared', 'exclusive', 'mixed') NOT NULL DEFAULT 'shared',
  `shared_recipient_count` INT NOT NULL DEFAULT 3,
  `city` VARCHAR(100) NULL,
  `suburb` VARCHAR(100) NULL,
  `province` VARCHAR(100) NULL,
  `property_type` ENUM(
    'apartment',
    'house',
    'villa',
    'plot',
    'commercial',
    'townhouse',
    'cluster_home',
    'farm',
    'shared_living'
  ) NULL,
  `min_bedrooms` INT NULL,
  `max_price` INT NULL,
  `min_price` INT NULL,
  `criteria` JSON NULL,
  `metadata` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_demand_campaigns_owner` (`owner_type`, `owner_id`),
  KEY `idx_demand_campaigns_status` (`status`),
  KEY `idx_demand_campaigns_source` (`source_channel`),
  CONSTRAINT `fk_demand_campaigns_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `demand_leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NULL,
  `source_channel` VARCHAR(100) NOT NULL,
  `status` ENUM('captured', 'assigned', 'unmatched') NOT NULL DEFAULT 'captured',
  `buyer_name` VARCHAR(200) NOT NULL,
  `buyer_email` VARCHAR(320) NOT NULL,
  `buyer_phone` VARCHAR(50) NULL,
  `message` TEXT NULL,
  `criteria` JSON NULL,
  `metadata` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_demand_leads_campaign` (`campaign_id`),
  KEY `idx_demand_leads_status` (`status`),
  KEY `idx_demand_leads_source` (`source_channel`),
  CONSTRAINT `fk_demand_leads_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `demand_campaigns` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `demand_lead_matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `demand_lead_id` INT NULL,
  `campaign_id` INT NULL,
  `lead_id` INT NOT NULL,
  `property_id` INT NULL,
  `agent_id` INT NULL,
  `owner_type` ENUM('agent', 'agency', 'developer', 'private') NOT NULL DEFAULT 'agent',
  `owner_id` INT NOT NULL,
  `match_score` DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
  `confidence` ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  `tier_weight` DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  `performance_multiplier` DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  `listing_quality_multiplier` DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  `fairness_multiplier` DECIMAL(8,4) NOT NULL DEFAULT 1.0000,
  `scoring_inputs` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_demand_lead_matches_demand_lead` (`demand_lead_id`),
  KEY `idx_demand_lead_matches_lead` (`lead_id`),
  KEY `idx_demand_lead_matches_campaign` (`campaign_id`),
  KEY `idx_demand_lead_matches_agent` (`agent_id`),
  KEY `idx_demand_lead_matches_score` (`match_score`),
  CONSTRAINT `fk_demand_matches_demand_lead` FOREIGN KEY (`demand_lead_id`) REFERENCES `demand_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_demand_matches_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `demand_campaigns` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_demand_matches_lead` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_demand_matches_property` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_demand_matches_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `demand_lead_assignments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `demand_lead_id` INT NULL,
  `campaign_id` INT NULL,
  `lead_id` INT NOT NULL,
  `assignment_group_id` VARCHAR(64) NOT NULL,
  `assignment_type` ENUM('shared', 'exclusive') NOT NULL DEFAULT 'shared',
  `assigned_agent_id` INT NULL,
  `owner_type` ENUM('agent', 'agency', 'developer', 'private') NOT NULL DEFAULT 'agent',
  `owner_id` INT NOT NULL,
  `rank_position` INT NOT NULL DEFAULT 1,
  `delivery_channels` JSON NULL,
  `status` ENUM('assigned', 'delivered', 'accepted', 'declined', 'expired') NOT NULL DEFAULT 'assigned',
  `reason` TEXT NULL,
  `assigned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delivered_at` TIMESTAMP NULL,
  `responded_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `idx_demand_lead_assignments_demand_lead` (`demand_lead_id`),
  KEY `idx_demand_lead_assignments_lead` (`lead_id`),
  KEY `idx_demand_lead_assignments_campaign` (`campaign_id`),
  KEY `idx_demand_lead_assignments_agent` (`assigned_agent_id`),
  KEY `idx_demand_lead_assignments_group` (`assignment_group_id`),
  KEY `idx_demand_lead_assignments_status` (`status`),
  CONSTRAINT `fk_demand_assignments_demand_lead` FOREIGN KEY (`demand_lead_id`) REFERENCES `demand_leads` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_demand_assignments_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `demand_campaigns` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_demand_assignments_lead` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_demand_assignments_agent` FOREIGN KEY (`assigned_agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `demand_unmatched_leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NULL,
  `source_channel` VARCHAR(100) NULL,
  `buyer_name` VARCHAR(200) NOT NULL,
  `buyer_email` VARCHAR(320) NOT NULL,
  `buyer_phone` VARCHAR(50) NULL,
  `criteria` JSON NULL,
  `payload` JSON NULL,
  `status` ENUM('open', 'resolved') NOT NULL DEFAULT 'open',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  KEY `idx_demand_unmatched_campaign` (`campaign_id`),
  KEY `idx_demand_unmatched_status` (`status`),
  KEY `idx_demand_unmatched_created` (`created_at`),
  CONSTRAINT `fk_demand_unmatched_campaign` FOREIGN KEY (`campaign_id`) REFERENCES `demand_campaigns` (`id`) ON DELETE SET NULL
);
