-- Referral Qualification Layer (MVP)
-- Creates versioned referral assessments, explainable matches, and optional document intake.

CREATE TABLE IF NOT EXISTS `referrals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference_code` VARCHAR(64) NOT NULL,
  `agent_id` INT NOT NULL,
  `client_name` VARCHAR(200) NOT NULL,
  `client_email` VARCHAR(320) NULL,
  `client_phone` VARCHAR(50) NULL,
  `preferred_areas` JSON NULL,
  `status` ENUM('quick', 'awaiting_documents', 'under_review', 'verified', 'submitted', 'viewing_booked') NOT NULL DEFAULT 'quick',
  `latest_assessment_id` INT NULL,
  `latest_assessment_version` INT NOT NULL DEFAULT 0,
  `latest_mode` ENUM('quick_qual', 'verified_qual') NOT NULL DEFAULT 'quick_qual',
  `latest_confidence_score` INT NOT NULL DEFAULT 0,
  `latest_affordability_min` INT NULL,
  `latest_affordability_max` INT NULL,
  `latest_monthly_payment_estimate` INT NULL,
  `last_submitted_program_id` INT NULL,
  `last_submitted_deal_id` INT NULL,
  `submitted_at` TIMESTAMP NULL,
  `created_by_user_id` INT NULL,
  `updated_by_user_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_referrals_reference_code` (`reference_code`),
  KEY `idx_referrals_agent` (`agent_id`),
  KEY `idx_referrals_status` (`status`),
  KEY `idx_referrals_updated_at` (`updated_at`),
  KEY `idx_referrals_last_submitted_deal` (`last_submitted_deal_id`),
  CONSTRAINT `fk_referrals_agent` FOREIGN KEY (`agent_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_referrals_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_referrals_updated_by` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_referrals_last_program` FOREIGN KEY (`last_submitted_program_id`) REFERENCES `distribution_programs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_referrals_last_deal` FOREIGN KEY (`last_submitted_deal_id`) REFERENCES `distribution_deals` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `referral_assessments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referral_id` INT NOT NULL,
  `version` INT NOT NULL,
  `mode` ENUM('quick_qual', 'verified_qual') NOT NULL DEFAULT 'quick_qual',
  `input_snapshot` JSON NOT NULL,
  `affordability_min` INT NOT NULL,
  `affordability_max` INT NOT NULL,
  `monthly_payment_estimate` INT NOT NULL,
  `confidence_score` INT NOT NULL DEFAULT 0,
  `confidence_factors` JSON NULL,
  `readiness_status` ENUM('quick_estimate', 'awaiting_documents', 'under_review', 'verified_estimate', 'matched_to_development', 'submitted_to_partner') NOT NULL DEFAULT 'quick_estimate',
  `flags` JSON NULL,
  `assumptions` JSON NULL,
  `improve_accuracy` JSON NULL,
  `disclaimer` TEXT NULL,
  `pdf_html` TEXT NULL,
  `upload_link_token` VARCHAR(96) NULL,
  `upload_link_expires_at` TIMESTAMP NULL,
  `document_count` INT NOT NULL DEFAULT 0,
  `matched_development_count` INT NOT NULL DEFAULT 0,
  `created_by_user_id` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_referral_assessments_referral_version` (`referral_id`, `version`),
  KEY `idx_referral_assessments_referral` (`referral_id`),
  KEY `idx_referral_assessments_readiness` (`readiness_status`),
  KEY `idx_referral_assessments_mode` (`mode`),
  KEY `idx_referral_assessments_created_at` (`created_at`),
  KEY `idx_referral_assessments_upload_token` (`upload_link_token`),
  CONSTRAINT `fk_referral_assessments_referral` FOREIGN KEY (`referral_id`) REFERENCES `referrals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_referral_assessments_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `referral_matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referral_id` INT NOT NULL,
  `assessment_id` INT NOT NULL,
  `development_id` INT NULL,
  `development_name` VARCHAR(255) NOT NULL,
  `area_label` VARCHAR(150) NULL,
  `rank_score` INT NOT NULL DEFAULT 0,
  `rank_position` INT NOT NULL,
  `match_bucket` ENUM('preferred_area', 'fallback_area') NOT NULL DEFAULT 'fallback_area',
  `match_reasons` JSON NULL,
  `qualifying_unit_types` JSON NULL,
  `metadata` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_referral_matches_referral` (`referral_id`),
  KEY `idx_referral_matches_assessment` (`assessment_id`),
  KEY `idx_referral_matches_development` (`development_id`),
  KEY `idx_referral_matches_bucket_score` (`match_bucket`, `rank_score`),
  CONSTRAINT `fk_referral_matches_referral` FOREIGN KEY (`referral_id`) REFERENCES `referrals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_referral_matches_assessment` FOREIGN KEY (`assessment_id`) REFERENCES `referral_assessments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_referral_matches_development` FOREIGN KEY (`development_id`) REFERENCES `developments` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `referral_documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referral_id` INT NOT NULL,
  `assessment_id` INT NULL,
  `document_type` ENUM('payslip', 'bank_statement', 'credit_report', 'id_document', 'proof_of_address', 'other') NOT NULL,
  `document_status` ENUM('requested', 'received', 'verified', 'rejected') NOT NULL DEFAULT 'requested',
  `uploaded_by` ENUM('agent', 'client', 'system') NOT NULL DEFAULT 'system',
  `file_name` VARCHAR(255) NULL,
  `file_url` TEXT NULL,
  `secure_token` VARCHAR(96) NULL,
  `consent_confirmed` TINYINT NOT NULL DEFAULT 0,
  `consent_text` VARCHAR(255) NULL,
  `metadata` JSON NULL,
  `reviewed_by_user_id` INT NULL,
  `reviewed_at` TIMESTAMP NULL,
  `uploaded_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_referral_documents_referral` (`referral_id`),
  KEY `idx_referral_documents_assessment` (`assessment_id`),
  KEY `idx_referral_documents_status` (`document_status`),
  KEY `idx_referral_documents_type` (`document_type`),
  KEY `idx_referral_documents_token` (`secure_token`),
  CONSTRAINT `fk_referral_documents_referral` FOREIGN KEY (`referral_id`) REFERENCES `referrals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_referral_documents_assessment` FOREIGN KEY (`assessment_id`) REFERENCES `referral_assessments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_referral_documents_reviewed_by` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
