CREATE TABLE `sl_places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(160) NOT NULL,
  `owner_user_id` INT NOT NULL,
  `address_line_private` VARCHAR(255) NOT NULL,
  `province_id` INT NULL,
  `city_id` INT NULL,
  `suburb_id` INT NULL,
  `geo_precision` ENUM('suburb','city','province') NOT NULL DEFAULT 'suburb',
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `place_kind` ENUM('house','apartment','townhouse','student_residence','other') NOT NULL DEFAULT 'other',
  `description` TEXT NULL,
  `status` ENUM('draft','pending_review','published','paused','archived') NOT NULL DEFAULT 'draft',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sl_places_slug` (`slug`),
  KEY `idx_sl_places_suburb` (`suburb_id`),
  KEY `idx_sl_places_city` (`city_id`),
  KEY `idx_sl_places_province` (`province_id`),
  KEY `idx_sl_places_status` (`status`),
  CONSTRAINT `fk_sl_places_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_sl_places_province` FOREIGN KEY (`province_id`) REFERENCES `provinces` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sl_places_city` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_sl_places_suburb` FOREIGN KEY (`suburb_id`) REFERENCES `suburbs` (`id`) ON DELETE SET NULL
);
