CREATE TABLE IF NOT EXISTS `development_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `development_id` int NOT NULL,
  `title` varchar(255) NOT NULL,
  `document_type` enum('price_list','house_plan','brochure','site_map','spec_sheet','availability_sheet','other') NOT NULL DEFAULT 'other',
  `category` enum('sales_asset','technical_asset','legal_asset','application_template','other') NOT NULL DEFAULT 'other',
  `storage_key` varchar(512) DEFAULT NULL,
  `file_url` varchar(2048) DEFAULT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `file_size_bytes` int DEFAULT NULL,
  `visibility` enum('internal','manager','referrer','public') NOT NULL DEFAULT 'internal',
  `downloadable` tinyint NOT NULL DEFAULT 1,
  `is_active` tinyint NOT NULL DEFAULT 1,
  `version` int NOT NULL DEFAULT 1,
  `replaced_by_document_id` int DEFAULT NULL,
  `uploaded_by` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_development_documents_development` (`development_id`),
  KEY `idx_development_documents_active` (`is_active`),
  KEY `idx_development_documents_visibility` (`visibility`),
  KEY `idx_development_documents_type` (`document_type`),
  KEY `idx_development_documents_uploaded_by` (`uploaded_by`),
  CONSTRAINT `fk_development_documents_development` FOREIGN KEY (`development_id`) REFERENCES `developments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_development_documents_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_development_documents_replaced_by` FOREIGN KEY (`replaced_by_document_id`) REFERENCES `development_documents` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `application_requirements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `development_id` int NOT NULL,
  `label` varchar(255) NOT NULL,
  `description` text,
  `required` tinyint NOT NULL DEFAULT 1,
  `provider` enum('buyer','referrer','manager','developer') NOT NULL DEFAULT 'buyer',
  `document_code` varchar(80) DEFAULT NULL,
  `accepted_file_types_json` json DEFAULT NULL,
  `linked_development_document_id` int DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT 0,
  `is_active` tinyint NOT NULL DEFAULT 1,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_application_requirements_development` (`development_id`),
  KEY `idx_application_requirements_active` (`is_active`),
  KEY `idx_application_requirements_required` (`required`),
  KEY `idx_application_requirements_provider` (`provider`),
  KEY `idx_application_requirements_order` (`development_id`,`sort_order`),
  CONSTRAINT `fk_application_requirements_development` FOREIGN KEY (`development_id`) REFERENCES `developments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_application_requirements_linked_document` FOREIGN KEY (`linked_development_document_id`) REFERENCES `development_documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_application_requirements_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_application_requirements_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `deal_requirement_statuses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `deal_id` int NOT NULL,
  `requirement_id` int NOT NULL,
  `uploaded_file_storage_key` varchar(512) DEFAULT NULL,
  `uploaded_file_url` varchar(2048) DEFAULT NULL,
  `uploaded_file_name` varchar(255) DEFAULT NULL,
  `linked_development_document_id` int DEFAULT NULL,
  `status` enum('missing','uploaded','pending_review','verified','rejected','waived') NOT NULL DEFAULT 'missing',
  `submitted_by` int DEFAULT NULL,
  `submitted_at` timestamp NULL DEFAULT NULL,
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text,
  `notes` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_deal_requirement_statuses_deal_requirement` (`deal_id`,`requirement_id`),
  KEY `idx_deal_requirement_statuses_deal` (`deal_id`),
  KEY `idx_deal_requirement_statuses_status` (`status`),
  KEY `idx_deal_requirement_statuses_requirement` (`requirement_id`),
  CONSTRAINT `fk_deal_requirement_statuses_deal` FOREIGN KEY (`deal_id`) REFERENCES `distribution_deals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_deal_requirement_statuses_requirement` FOREIGN KEY (`requirement_id`) REFERENCES `application_requirements` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_deal_requirement_statuses_linked_document` FOREIGN KEY (`linked_development_document_id`) REFERENCES `development_documents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_deal_requirement_statuses_submitted_by` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_deal_requirement_statuses_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
