CREATE TABLE IF NOT EXISTS `development_approval_queue` (`id` int AUTO_INCREMENT NOT NULL,`development_id` int NOT NULL,`submitted_by` int NOT NULL,`status` enum('pending','reviewing','approved','rejected','changes_requested') NOT NULL DEFAULT 'pending',`submission_type` enum('initial','update') NOT NULL DEFAULT 'initial',`review_notes` text,`rejection_reason` text,`compliance_checks` json,`submitted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`reviewed_at` timestamp NULL,`reviewed_by` int NULL,PRIMARY KEY(`id`),KEY `idx_dev_approval_status`(`status`),KEY `idx_dev_approval_dev_id`(`development_id`),KEY `idx_dev_approval_submitted_by`(`submitted_by`),KEY `idx_dev_approval_reviewed_by`(`reviewed_by`),CONSTRAINT `development_approval_queue_development_id_developments_id_fk` FOREIGN KEY(`development_id`) REFERENCES `developments`(`id`) ON DELETE CASCADE,CONSTRAINT `development_approval_queue_submitted_by_users_id_fk` FOREIGN KEY(`submitted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT,CONSTRAINT `development_approval_queue_reviewed_by_users_id_fk` FOREIGN KEY(`reviewed_by`) REFERENCES `users`(`id`) ON DELETE SET NULL);
ALTER TABLE `development_approval_queue` MODIFY COLUMN `status` enum('pending','reviewing','approved','rejected','changes_requested') NOT NULL DEFAULT 'pending', MODIFY COLUMN `submission_type` enum('initial','update') NOT NULL DEFAULT 'initial', MODIFY COLUMN `reviewed_by` int NULL;
-- RECONCILE INDEX: status
SET @has_status_leading_index=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='development_approval_queue' AND COLUMN_NAME='status' AND SEQ_IN_INDEX=1); SET @sql_status_index=IF(@has_status_leading_index=0,'ALTER TABLE `development_approval_queue` ADD INDEX `idx_dev_approval_status` (`status`)','SELECT 1'); PREPARE stmt_status_index FROM @sql_status_index; EXECUTE stmt_status_index; DEALLOCATE PREPARE stmt_status_index;
-- RECONCILE INDEX: development_id
SET @has_development_id_leading_index=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='development_approval_queue' AND COLUMN_NAME='development_id' AND SEQ_IN_INDEX=1); SET @sql_development_id_index=IF(@has_development_id_leading_index=0,'ALTER TABLE `development_approval_queue` ADD INDEX `idx_dev_approval_dev_id` (`development_id`)','SELECT 1'); PREPARE stmt_development_id_index FROM @sql_development_id_index; EXECUTE stmt_development_id_index; DEALLOCATE PREPARE stmt_development_id_index;
-- RECONCILE INDEX: submitted_by
SET @has_submitted_by_leading_index=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='development_approval_queue' AND COLUMN_NAME='submitted_by' AND SEQ_IN_INDEX=1); SET @sql_submitted_by_index=IF(@has_submitted_by_leading_index=0,'ALTER TABLE `development_approval_queue` ADD INDEX `idx_dev_approval_submitted_by` (`submitted_by`)','SELECT 1'); PREPARE stmt_submitted_by_index FROM @sql_submitted_by_index; EXECUTE stmt_submitted_by_index; DEALLOCATE PREPARE stmt_submitted_by_index;
-- RECONCILE INDEX: reviewed_by
SET @has_reviewed_by_leading_index=(SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='development_approval_queue' AND COLUMN_NAME='reviewed_by' AND SEQ_IN_INDEX=1); SET @sql_reviewed_by_index=IF(@has_reviewed_by_leading_index=0,'ALTER TABLE `development_approval_queue` ADD INDEX `idx_dev_approval_reviewed_by` (`reviewed_by`)','SELECT 1'); PREPARE stmt_reviewed_by_index FROM @sql_reviewed_by_index; EXECUTE stmt_reviewed_by_index; DEALLOCATE PREPARE stmt_reviewed_by_index;
-- RECONCILE FK: development_id
SET @correct_development_id_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='development_id' AND kcu.REFERENCED_TABLE_NAME='developments' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE='CASCADE');
SET @existing_development_id_fk=NULL;
SET @existing_development_id_fk=(SELECT MIN(kcu.CONSTRAINT_NAME) FROM information_schema.KEY_COLUMN_USAGE kcu WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='development_id' AND kcu.REFERENCED_TABLE_NAME IS NOT NULL);
SET @drop_development_id_fk_sql=IF(@correct_development_id_fk_count>0 OR @existing_development_id_fk IS NULL,'SELECT 1',CONCAT('ALTER TABLE `development_approval_queue` DROP FOREIGN KEY `',REPLACE(@existing_development_id_fk,'`','``'),'`'));
PREPARE stmt_drop_development_id_fk FROM @drop_development_id_fk_sql; EXECUTE stmt_drop_development_id_fk; DEALLOCATE PREPARE stmt_drop_development_id_fk;
SET @correct_development_id_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='development_id' AND kcu.REFERENCED_TABLE_NAME='developments' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE='CASCADE');
SET @add_development_id_fk_sql=IF(@correct_development_id_fk_count>0,'SELECT 1','ALTER TABLE `development_approval_queue` ADD CONSTRAINT `development_approval_queue_development_id_developments_id_fk` FOREIGN KEY (`development_id`) REFERENCES `developments` (`id`) ON DELETE CASCADE');
PREPARE stmt_add_development_id_fk FROM @add_development_id_fk_sql; EXECUTE stmt_add_development_id_fk; DEALLOCATE PREPARE stmt_add_development_id_fk;
-- RECONCILE FK: submitted_by
SET @correct_submitted_by_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='submitted_by' AND kcu.REFERENCED_TABLE_NAME='users' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE IN ('RESTRICT','NO ACTION'));
SET @existing_submitted_by_fk=NULL;
SET @existing_submitted_by_fk=(SELECT MIN(kcu.CONSTRAINT_NAME) FROM information_schema.KEY_COLUMN_USAGE kcu WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='submitted_by' AND kcu.REFERENCED_TABLE_NAME IS NOT NULL);
SET @drop_submitted_by_fk_sql=IF(@correct_submitted_by_fk_count>0 OR @existing_submitted_by_fk IS NULL,'SELECT 1',CONCAT('ALTER TABLE `development_approval_queue` DROP FOREIGN KEY `',REPLACE(@existing_submitted_by_fk,'`','``'),'`'));
PREPARE stmt_drop_submitted_by_fk FROM @drop_submitted_by_fk_sql; EXECUTE stmt_drop_submitted_by_fk; DEALLOCATE PREPARE stmt_drop_submitted_by_fk;
SET @correct_submitted_by_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='submitted_by' AND kcu.REFERENCED_TABLE_NAME='users' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE IN ('RESTRICT','NO ACTION'));
SET @add_submitted_by_fk_sql=IF(@correct_submitted_by_fk_count>0,'SELECT 1','ALTER TABLE `development_approval_queue` ADD CONSTRAINT `development_approval_queue_submitted_by_users_id_fk` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
PREPARE stmt_add_submitted_by_fk FROM @add_submitted_by_fk_sql; EXECUTE stmt_add_submitted_by_fk; DEALLOCATE PREPARE stmt_add_submitted_by_fk;
-- RECONCILE FK: reviewed_by
ALTER TABLE `development_approval_queue` MODIFY COLUMN `reviewed_by` int NULL;
SET @correct_reviewed_by_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='reviewed_by' AND kcu.REFERENCED_TABLE_NAME='users' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE='SET NULL');
SET @existing_reviewed_by_fk=NULL;
SET @existing_reviewed_by_fk=(SELECT MIN(kcu.CONSTRAINT_NAME) FROM information_schema.KEY_COLUMN_USAGE kcu WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='reviewed_by' AND kcu.REFERENCED_TABLE_NAME IS NOT NULL);
SET @drop_reviewed_by_fk_sql=IF(@correct_reviewed_by_fk_count>0 OR @existing_reviewed_by_fk IS NULL,'SELECT 1',CONCAT('ALTER TABLE `development_approval_queue` DROP FOREIGN KEY `',REPLACE(@existing_reviewed_by_fk,'`','``'),'`'));
PREPARE stmt_drop_reviewed_by_fk FROM @drop_reviewed_by_fk_sql; EXECUTE stmt_drop_reviewed_by_fk; DEALLOCATE PREPARE stmt_drop_reviewed_by_fk;
SET @correct_reviewed_by_fk_count=(SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE kcu JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON kcu.CONSTRAINT_SCHEMA=rc.CONSTRAINT_SCHEMA AND kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME AND kcu.TABLE_NAME=rc.TABLE_NAME WHERE kcu.CONSTRAINT_SCHEMA=DATABASE() AND kcu.TABLE_SCHEMA=DATABASE() AND kcu.TABLE_NAME='development_approval_queue' AND kcu.COLUMN_NAME='reviewed_by' AND kcu.REFERENCED_TABLE_NAME='users' AND kcu.REFERENCED_COLUMN_NAME='id' AND rc.DELETE_RULE='SET NULL');
SET @add_reviewed_by_fk_sql=IF(@correct_reviewed_by_fk_count>0,'SELECT 1','ALTER TABLE `development_approval_queue` ADD CONSTRAINT `development_approval_queue_reviewed_by_users_id_fk` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL');
PREPARE stmt_add_reviewed_by_fk FROM @add_reviewed_by_fk_sql; EXECUTE stmt_add_reviewed_by_fk; DEALLOCATE PREPARE stmt_add_reviewed_by_fk;
