-- P2 pre-launch cutover: relational delivery obligations and append-only attempts
CREATE TABLE `lead_deliveries` (
  `id` int AUTO_INCREMENT NOT NULL,
  `lead_id` int NOT NULL,
  `purpose` enum('primary_custody','notification','platform_action') NOT NULL,
  `routing_revision` int NOT NULL DEFAULT 1,
  `channel` enum('crm_export','email','manual','none') NOT NULL,
  `recipient_type` enum('agent','agency','developer','manual') NOT NULL,
  `recipient_user_id` int,
  `recipient_agent_id` int,
  `recipient_agency_id` int,
  `recipient_developer_organisation_id` int,
  `recipient_publisher_id` int,
  `destination_name` varchar(255),
  `destination_address` varchar(320),
  `destination_snapshot` json,
  `supply_origin` enum('customer_managed','platform_curated','shared_living') NOT NULL,
  `lead_custody` enum('verified_customer_recipient','platform_managed','attention_required') NOT NULL,
  `state` enum('queued','claimed','accepted','completed','retryable_failed','exhausted','unknown','cancelled','superseded') NOT NULL DEFAULT 'queued',
  `idempotency_key` varchar(255) NOT NULL,
  `due_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `max_attempts` int NOT NULL DEFAULT 3,
  `completed_at` timestamp(6) NULL,
  `superseded_at` timestamp(6) NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lead_deliveries_idempotency` (`idempotency_key`),
  UNIQUE KEY `uq_lead_deliveries_lead_purpose_revision` (`lead_id`,`purpose`,`routing_revision`),
  KEY `idx_lead_deliveries_due` (`state`,`due_at`),
  KEY `idx_lead_deliveries_lead_current` (`lead_id`,`purpose`,`routing_revision`,`state`),
  KEY `idx_lead_deliveries_recipient_agent` (`recipient_agent_id`,`state`),
  KEY `idx_lead_deliveries_recipient_agency` (`recipient_agency_id`,`state`),
  KEY `idx_lead_deliveries_recipient_developer` (`recipient_developer_organisation_id`,`state`),
  KEY `idx_lead_deliveries_recipient_user` (`recipient_user_id`,`state`),
  CONSTRAINT `lead_deliveries_lead_id_fk` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_deliveries_recipient_user_id_fk` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lead_deliveries_recipient_agent_id_fk` FOREIGN KEY (`recipient_agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lead_deliveries_recipient_agency_id_fk` FOREIGN KEY (`recipient_agency_id`) REFERENCES `agencies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lead_deliveries_recipient_developer_id_fk` FOREIGN KEY (`recipient_developer_organisation_id`) REFERENCES `developer_organisations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `lead_deliveries_recipient_publisher_id_fk` FOREIGN KEY (`recipient_publisher_id`) REFERENCES `catalogue_publishers` (`id`) ON DELETE SET NULL
);

CREATE TABLE `lead_delivery_attempts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `delivery_id` int NOT NULL,
  `attempt_number` int NOT NULL,
  `state` enum('queued','claimed','accepted','completed','retryable_failed','exhausted','unknown','expired') NOT NULL DEFAULT 'queued',
  `lease_token` varchar(128),
  `lease_generation` int NOT NULL DEFAULT 0,
  `claimed_at` timestamp(6) NULL,
  `lease_expires_at` timestamp(6) NULL,
  `accepted_at` timestamp(6) NULL,
  `completed_at` timestamp(6) NULL,
  `provider_reference` varchar(255),
  `error_code` varchar(100),
  `error_message` varchar(1000),
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_lead_delivery_attempt_number` (`delivery_id`,`attempt_number`),
  UNIQUE KEY `uq_lead_delivery_attempt_lease` (`lease_token`),
  KEY `idx_lead_delivery_attempts_delivery` (`delivery_id`,`attempt_number`),
  KEY `idx_lead_delivery_attempts_claim_expiry` (`state`,`lease_expires_at`),
  KEY `idx_lead_delivery_attempts_provider_reference` (`provider_reference`),
  CONSTRAINT `lead_delivery_attempts_delivery_id_fk` FOREIGN KEY (`delivery_id`) REFERENCES `lead_deliveries` (`id`) ON DELETE CASCADE
);

ALTER TABLE `leads` DROP COLUMN `delivery_attempts`;
