-- B10: durable provider-delivery obligation, distinct from its business event.
CREATE TABLE `transactional_email_deliveries` (
  `id` int AUTO_INCREMENT NOT NULL,
  `source_type` enum('billing_audit','term_notice','agency_invitation') NOT NULL,
  `source_id` int NOT NULL,
  `source_version` varchar(64),
  `purpose` varchar(80) NOT NULL,
  `recipient_user_id` int,
  `recipient_email` varchar(320) NOT NULL,
  `delivery_key` varchar(160) NOT NULL,
  `state` enum('pending','claimed','accepted','retryable_failed','permanent_failed','unknown','cancelled') NOT NULL DEFAULT 'pending',
  `attempt_count` int NOT NULL DEFAULT 0,
  `max_attempts` int NOT NULL DEFAULT 3,
  `next_attempt_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `claim_token` varchar(64),
  `claim_expires_at` timestamp(6),
  `provider_reference` varchar(255),
  `last_error_code` varchar(80),
  `last_error` varchar(500),
  `accepted_at` timestamp(6),
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_transactional_email_delivery_key` (`delivery_key`),
  KEY `idx_transactional_email_due` (`state`,`next_attempt_at`),
  KEY `idx_transactional_email_claim_expiry` (`state`,`claim_expires_at`),
  KEY `idx_transactional_email_source` (`source_type`,`source_id`),
  CONSTRAINT `transactional_email_deliveries_recipient_user_id_fk` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
);
