import type { FeedItem } from './model';

export const mockFeedItems: FeedItem[] = [
  {
    id: 'listing-rosebank-penthouse',
    kind: 'listing',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    posterUrl: 'https://placehold.co/1080x1920/0f172a/ffffff?text=Rosebank+Penthouse',
    caption: 'Sunset skyline views from this 3-bed Rosebank penthouse.',
    linkedListing: {
      title: 'Rosebank Sky Penthouse',
      price: 'R4,200,000',
      location: 'Rosebank, Johannesburg',
      beds: 3,
      baths: 2,
      size: '176 sqm',
      amenities: ['Rooftop pool', 'Backup power', '24h security', 'Pet friendly'],
      listingUrl: '/property/rosebank-sky-penthouse',
      agentContact: {
        name: 'Lindiwe Mokoena',
        organization: 'Atlas Prime Realty',
        phone: '+27 11 555 0132',
        whatsapp: '+27 82 444 2211',
        email: 'lindiwe@atlasprime.co.za',
      },
    },
  },
  {
    id: 'agent-lindiwe-north',
    kind: 'agent',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    posterUrl: 'https://placehold.co/1080x1920/1f2937/ffffff?text=Agent+Feature',
    caption: 'Meet Lindiwe, helping families move across the northern suburbs.',
    agentProfile: {
      name: 'Lindiwe Mokoena',
      agency: 'Atlas Prime Realty',
      areaServed: 'Sandton, Fourways, Bryanston',
      bio: 'Residential specialist focused on move-up buyers and first-time investors.',
      phone: '+27 11 555 0132',
      whatsapp: '+27 82 444 2211',
      email: 'lindiwe@atlasprime.co.za',
    },
  },
  {
    id: 'partner-kitchen-upgrade',
    kind: 'partner',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    posterUrl: 'https://placehold.co/1080x1920/111827/ffffff?text=Partner+Showcase',
    caption: 'Budget kitchen refresh with modern finishes in under 4 weeks.',
    partnerShowcase: {
      projectTitle: 'Modern Kitchen Upgrade',
      areaServed: 'Johannesburg North',
      scope: 'Demolition, cabinetry, stone tops, splashback, lighting',
      priceRange: 'R95,000 - R180,000',
      beforeImageUrl: 'https://placehold.co/640x360/334155/ffffff?text=Before',
      afterImageUrl: 'https://placehold.co/640x360/0ea5e9/ffffff?text=After',
      contact: {
        name: 'Buildline Renovations',
        organization: 'Buildline Renovations',
        phone: '+27 10 555 9912',
        whatsapp: '+27 79 005 9912',
        email: 'quotes@buildline.co.za',
      },
    },
  },
  {
    id: 'listing-umhlanga-ocean',
    kind: 'listing',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    posterUrl: 'https://placehold.co/1080x1920/082f49/ffffff?text=Umhlanga+Apartment',
    caption: 'Lock-up-and-go beachfront apartment with hotel-grade amenities.',
    linkedListing: {
      title: 'Oceanside View Apartment',
      price: 'R2,850,000',
      location: 'Umhlanga Rocks, Durban',
      beds: 2,
      baths: 2,
      size: '118 sqm',
      amenities: ['Ocean view', 'Gym', 'Concierge', '2 parking bays'],
      listingUrl: '/property/oceanside-view-apartment',
      agentContact: {
        name: 'Nadia Pillay',
        organization: 'Coastal Key Properties',
        phone: '+27 31 555 1108',
        whatsapp: '+27 84 778 3320',
        email: 'nadia@coastalkey.co.za',
      },
    },
  },
  {
    id: 'agent-cobus-cape',
    kind: 'agent',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    posterUrl: 'https://placehold.co/1080x1920/312e81/ffffff?text=Agent+Spotlight',
    caption: 'Cobus on buying in high-demand Cape Town lifestyle suburbs.',
    agentProfile: {
      name: 'Cobus van Zyl',
      agency: 'Coastal Key Properties',
      areaServed: 'Sea Point, Green Point, Camps Bay',
      bio: 'Luxury coastal broker with 12+ years in premium apartment transactions.',
      phone: '+27 21 555 8144',
      whatsapp: '+27 72 881 1299',
      email: 'cobus@coastalkey.co.za',
    },
  },
  {
    id: 'partner-bathroom-remodel',
    kind: 'partner',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    posterUrl: 'https://placehold.co/1080x1920/3f3f46/ffffff?text=Renovation+Partner',
    caption: 'Primary bathroom remodel with walk-in shower and custom vanity.',
    partnerShowcase: {
      projectTitle: 'Premium Bathroom Remodel',
      areaServed: 'Pretoria East',
      scope: 'Plumbing reroute, tiling, frameless shower, vanity install',
      priceRange: 'R70,000 - R130,000',
      beforeImageUrl: 'https://placehold.co/640x360/475569/ffffff?text=Before',
      afterImageUrl: 'https://placehold.co/640x360/16a34a/ffffff?text=After',
      contact: {
        name: 'Tile & Tone Studio',
        organization: 'Tile & Tone Studio',
        phone: '+27 12 555 7091',
        whatsapp: '+27 72 900 7091',
        email: 'hello@tiletone.co.za',
      },
    },
  },
  {
    id: 'listing-waterfall-estate',
    kind: 'listing',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    posterUrl: 'https://placehold.co/1080x1920/1e293b/ffffff?text=Estate+Home',
    caption: 'Estate living with private garden, study nook, and solar backup.',
    linkedListing: {
      title: 'Waterfall Family Home',
      price: 'R3,100,000',
      location: 'Waterfall, Midrand',
      beds: 4,
      baths: 3,
      size: '240 sqm',
      amenities: ['Solar backup', 'Estate clubhouse', 'Fibre ready', 'Double garage'],
      listingUrl: '/property/waterfall-family-home',
      agentContact: {
        name: 'Mpho Dlamini',
        organization: 'Urban Shift Residential',
        phone: '+27 11 555 1440',
        whatsapp: '+27 82 741 2033',
        email: 'mpho@urbanshift.co.za',
      },
    },
  },
  {
    id: 'agent-ayanda-pretoria',
    kind: 'agent',
    videoUrl:
      'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    posterUrl: 'https://placehold.co/1080x1920/374151/ffffff?text=Agent+Insight',
    caption: 'Ayanda shares how she matches rentals to relocation clients.',
    agentProfile: {
      name: 'Ayanda Ndlovu',
      agency: 'Urban Shift Residential',
      areaServed: 'Menlyn, Brooklyn, Lynnwood',
      bio: 'Client-first rental and resale advisor for young professionals and families.',
      phone: '+27 12 555 2041',
      whatsapp: '+27 83 319 1100',
      email: 'ayanda@urbanshift.co.za',
    },
  },
  {
    id: 'partner-landscaping-revamp',
    kind: 'partner',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    posterUrl: 'https://placehold.co/1080x1920/064e3b/ffffff?text=Outdoor+Upgrade',
    caption: 'Outdoor revamp that boosted curb appeal and tenant inquiries.',
    partnerShowcase: {
      projectTitle: 'Landscaping + Patio Revamp',
      areaServed: 'Cape Town Southern Suburbs',
      scope: 'Garden redesign, paving, irrigation, exterior lighting',
      priceRange: 'R45,000 - R140,000',
      beforeImageUrl: 'https://placehold.co/640x360/166534/ffffff?text=Before',
      afterImageUrl: 'https://placehold.co/640x360/15803d/ffffff?text=After',
      contact: {
        name: 'Greenframe Outdoor Co.',
        organization: 'Greenframe Outdoor Co.',
        phone: '+27 21 555 8781',
        whatsapp: '+27 83 990 8781',
        email: 'quotes@greenframe.co.za',
      },
    },
  },
  {
    id: 'listing-ballito-villa',
    kind: 'listing',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    posterUrl: 'https://placehold.co/1080x1920/0c4a6e/ffffff?text=Ballito+Villa',
    caption: 'Coastal villa with entertainer deck and sea breeze year-round.',
    linkedListing: {
      title: 'Ballito Coastal Villa',
      price: 'R6,750,000',
      location: 'Ballito, KwaZulu-Natal',
      beds: 5,
      baths: 4,
      size: '410 sqm',
      amenities: ['Sea-facing deck', 'Smart home', 'Pool', 'Staff quarters'],
      listingUrl: '/property/ballito-coastal-villa',
      agentContact: {
        name: 'Sizwe Khumalo',
        organization: 'Coastal Key Properties',
        phone: '+27 32 555 2201',
        whatsapp: '+27 76 111 4200',
        email: 'sizwe@coastalkey.co.za',
      },
    },
  },
];
